begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(35);

select ok(exists(select 1 from identity.permissions where code='audit.events.read'),'audit events read permission exists');
select ok(exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id join identity.roles r on r.id=rp.role_id where p.code='audit.events.read' and lower(r.code)='association_admin' and rp.effect='allow'),'association_admin role receives audit permission');
select ok(exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id join identity.roles r on r.id=rp.role_id where p.code='audit.events.read' and lower(r.code)='property_manager' and rp.effect='allow'),'property_manager role receives audit permission');
select ok(exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id join identity.roles r on r.id=rp.role_id where p.code='audit.events.read' and lower(r.code)='president' and rp.effect='allow'),'president role receives audit permission');
select ok(exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id join identity.roles r on r.id=rp.role_id where p.code='audit.events.read' and lower(r.code)='censor' and rp.effect='allow'),'censor role receives audit permission');
select ok(not exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id join identity.roles r on r.id=rp.role_id where p.code='audit.events.read' and lower(r.code)='owner'),'owner role never receives audit permission');
select ok(not exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id join identity.roles r on r.id=rp.role_id where p.code='audit.events.read' and lower(r.code)='tenant_resident'),'tenant resident role never receives audit permission');
select ok(exists(select 1 from pg_proc where oid='audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure),'customer audit RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure),'RPC executes with security definer');
select ok(position('auth.uid() is null' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'authentication required check enforced');
select ok(position('app_private.customer_mfa_required()' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'customer MFA check enforced');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'AAL2 session verified when MFA required');
select ok(position($n$m.status = 'active'$n$ in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at <= statement_timestamp()' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'membership time bounds enforced');
select ok(position('g.starts_at <= statement_timestamp()' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'context grant time bounds enforced');
select ok(position($n$lower(v.role_code) not in ('association_admin', 'property_manager', 'president', 'censor')$n$ in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'management role allowlist strictly enforced');
select ok(position($n$p.code = 'audit.events.read'$n$ in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'audit.events.read permission required');
select ok(position($n$w.lifecycle_status = 'ACTIVE'$n$ in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'workspace active lifecycle status required');
select ok(position('e.tenant_id = v.tenant_id' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'tenant isolation strictly enforced');
select ok(position('v.scope_type' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'context scope filtering enforced');
select ok(position('p_limit > 100' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'pagination bounded to maximum 100');
select ok(position('p_limit < 1' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'pagination lower bound enforced');
select ok(position('p_from > p_until' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'date range validated');
select ok(position('app_private.redact_audit_text(e.reason)' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'reason redacted via app_private.redact_audit_text');
select ok(position('before_snapshot' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0 and position($n$'before_snapshot', e.before_snapshot$n$ in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))=0,'before snapshot never projected to client');
select ok(position('after_snapshot' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0 and position($n$'after_snapshot', e.after_snapshot$n$ in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))=0,'after snapshot never projected to client');
select ok(position('e.actor_id as actor_id' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))=0,'raw actor id never projected to client');
select ok((select proisstrict is false from pg_proc where oid='audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure),'RPC handles null arguments safely');
select ok(not has_function_privilege('anon','audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)','EXECUTE'),'anon cannot execute customer audit RPC');
select ok(not has_function_privilege('public','audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)','EXECUTE'),'public cannot execute customer audit RPC');
select ok(has_function_privilege('authenticated','audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)','EXECUTE'),'authenticated can execute gated customer audit RPC');
select ok(position('p_query' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'query text filtering supported');
select ok(position('p_action' in pg_get_functiondef('audit.get_customer_events(uuid,integer,integer,text,text,timestamptz,timestamptz)'::regprocedure))>0,'action filtering supported');

select * from finish();
rollback;
