begin;
select plan(37);
select has_table('finance','export_artifact_scan_attestations','scanner attestation registry exists');
select ok(exists(select 1 from information_schema.columns where table_schema='finance' and table_name='export_artifacts' and column_name='object_path'),'artifact object path exists');
select ok(exists(select 1 from information_schema.columns where table_schema='finance' and table_name='export_artifacts' and column_name='scan_status'),'artifact scanner state exists');
select ok(exists(select 1 from information_schema.columns where table_schema='finance' and table_name='export_artifacts' and column_name='scan_completed_at'),'scanner completion time exists');
select ok((select not public and file_size_limit=5242880 from storage.buckets where id='export-artifact-vault'),'artifact vault is private and bounded');
select ok((select allowed_mime_types @> array['application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv'] from storage.buckets where id='export-artifact-vault'),'artifact MIME allowlist is exact-capable');
select ok((select relrowsecurity from pg_class where oid='finance.export_artifact_scan_attestations'::regclass),'attestations use RLS defense in depth');
select ok(not has_table_privilege('authenticated','finance.export_artifact_scan_attestations','SELECT'),'customers cannot read raw attestations');
select ok(not has_table_privilege('authenticated','finance.export_artifact_scan_attestations','INSERT'),'customers cannot forge attestations');
select ok(not has_table_privilege('anon','finance.export_artifact_scan_attestations','SELECT'),'anonymous users cannot read attestations');
select has_function('customer_api','prepare_export_artifact_v2',array['uuid','uuid','text','text','text','bigint'],'quarantine preparation gateway exists');
select has_function('customer_api','authorize_export_artifact_download_v1',array['uuid','uuid','text','text'],'controlled download gateway exists');
select has_function('app_private','record_export_artifact_scan_v1',array['uuid','text','text','text','text','text','text','timestamp with time zone'],'provider attestation ingress exists');
select has_function('app_private','export_artifact_storage_allowed_v1',array['text','text'],'storage policy helper exists');
select ok(has_function_privilege('authenticated','customer_api.prepare_export_artifact_v2(uuid,uuid,text,text,text,bigint)','EXECUTE'),'authenticated may invoke guarded preparation');
select ok(has_function_privilege('authenticated','customer_api.authorize_export_artifact_download_v1(uuid,uuid,text,text)','EXECUTE'),'authenticated may invoke guarded download authorization');
select ok(not has_function_privilege('anon','customer_api.prepare_export_artifact_v2(uuid,uuid,text,text,text,bigint)','EXECUTE'),'anonymous preparation is denied');
select ok(not has_function_privilege('authenticated','app_private.record_export_artifact_scan_v1(uuid,text,text,text,text,text,text,timestamp with time zone)','EXECUTE'),'authenticated cannot attest scans');
select ok(has_function_privilege('service_role','app_private.record_export_artifact_scan_v1(uuid,text,text,text,text,text,text,timestamp with time zone)','EXECUTE'),'trusted service integration may attest scans');
select ok(position('scanning_pending' in pg_get_functiondef('app_private.prepare_export_artifact_internal_v2(uuid,uuid,text,text,text,bigint)'::regprocedure))>0,'materialization starts scanner pending');
select ok(position('export_artifact_materialization_mismatch' in pg_get_functiondef('app_private.prepare_export_artifact_internal_v2(uuid,uuid,text,text,text,bigint)'::regprocedure))>0,'materialization retry mismatch fails closed');
select ok(position('export_scan_content_mismatch' in pg_get_functiondef('app_private.record_export_artifact_scan_v1(uuid,text,text,text,text,text,text,timestamp with time zone)'::regprocedure))>0,'scan hash mismatch fails closed');
select ok(position('export_artifact_object_missing' in pg_get_functiondef('app_private.record_export_artifact_scan_v1(uuid,text,text,text,text,text,text,timestamp with time zone)'::regprocedure))>0,'scan verdict requires stored object');
select ok(position('export_scan_already_finalized' in pg_get_functiondef('app_private.record_export_artifact_scan_v1(uuid,text,text,text,text,text,text,timestamp with time zone)'::regprocedure))>0,'conflicting scanner replay is rejected');
select ok(position('when ''clean'' then ''clean''' in pg_get_functiondef('app_private.record_export_artifact_scan_v1(uuid,text,text,text,text,text,text,timestamp with time zone)'::regprocedure))>0,'only explicit clean verdict releases artifact');
select ok(position('export_artifact_scan_pending' in pg_get_functiondef('app_private.authorize_export_artifact_download_internal_v1(uuid,uuid,text,text)'::regprocedure))>0,'pending scan blocks download deterministically');
select ok(position('export_artifact_quarantined' in pg_get_functiondef('app_private.authorize_export_artifact_download_internal_v1(uuid,uuid,text,text)'::regprocedure))>0,'malicious artifact blocks download deterministically');
select ok(position('export_artifact_scan_failed' in pg_get_functiondef('app_private.authorize_export_artifact_download_internal_v1(uuid,uuid,text,text)'::regprocedure))>0,'scanner error blocks download deterministically');
select ok(position('scan_status<>''clean''' in replace(pg_get_functiondef('app_private.authorize_export_artifact_download_internal_v1(uuid,uuid,text,text)'::regprocedure),' ',''))>0,'download requires clean status');
select ok(exists(select 1 from pg_trigger where tgrelid='finance.export_artifact_scan_attestations'::regclass and tgname='export_scan_attestations_immutable' and not tgisinternal),'attestations are immutable');
select ok(exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='export_artifact_vault_insert' and cmd='INSERT'),'bound quarantine upload policy exists');
select ok(position('generated_by' in pg_get_functiondef('app_private.export_artifact_storage_allowed_v1(text,text)'::regprocedure))>0,'storage access binds the generating user');
select ok(exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='export_artifact_vault_clean_select' and cmd='SELECT'),'clean-only download policy exists');
select ok(position('scan_status=''clean''' in replace(pg_get_functiondef('app_private.export_artifact_storage_allowed_v1(text,text)'::regprocedure),' ',''))>0,'storage read requires clean scanner state');
select ok(not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd in ('UPDATE','DELETE') and (coalesce(qual,'')||coalesce(with_check,'')) like '%export-artifact-vault%'),'customer overwrite and deletion remain unavailable');
select ok(position('EXPORT_ARTIFACT_SCAN_ATTESTED' in pg_get_functiondef('app_private.record_export_artifact_scan_v1(uuid,text,text,text,text,text,text,timestamp with time zone)'::regprocedure))>0,'scanner verdict emits audit evidence');
select ok(not has_function_privilege('anon','app_private.export_artifact_storage_allowed_v1(text,text)','EXECUTE'),'anonymous storage helper access is denied');
select * from finish();
rollback;
