begin;
select plan(43);
select has_table('finance','export_artifact_scan_jobs','durable scan job registry exists');
select ok((select relrowsecurity from pg_class where oid='finance.export_artifact_scan_jobs'::regclass),'scan jobs use RLS defense in depth');
select ok(not has_table_privilege('authenticated','finance.export_artifact_scan_jobs','SELECT'),'customers cannot inspect scan jobs');
select ok(not has_table_privilege('authenticated','finance.export_artifact_scan_jobs','UPDATE'),'customers cannot mutate scan jobs');
select ok(not has_table_privilege('service_role','finance.export_artifact_scan_jobs','UPDATE'),'worker cannot bypass controlled gateways');
select ok(exists(select 1 from pg_constraint where conrelid='finance.export_artifact_scan_jobs'::regclass and contype='u' and pg_get_constraintdef(oid) like '%artifact_id%'),'one durable job exists per artifact');
select ok(exists(select 1 from pg_indexes where schemaname='finance' and tablename='export_artifact_scan_jobs' and indexname='export_artifact_scan_jobs_ready_idx'),'ready-job index exists');
select ok(exists(select 1 from pg_indexes where schemaname='finance' and tablename='export_artifact_scan_jobs' and indexname='export_artifact_scan_jobs_tenant_idx'),'tenant evidence index exists');
select ok(exists(select 1 from pg_policies where schemaname='finance' and tablename='export_artifact_scan_jobs' and policyname='export_artifact_scan_jobs_direct_deny'),'explicit direct-deny policy exists');
select ok(exists(select 1 from pg_trigger where tgrelid='finance.export_artifacts'::regclass and tgname='export_artifact_scan_job_enqueue' and not tgisinternal),'pending artifact automatically enqueues');
select has_function('app_private','claim_export_artifact_scan_job_v1',array['text','text','integer'],'atomic worker lease gateway exists');
select has_function('app_private','fail_export_artifact_scan_job_v1',array['uuid','uuid','text','integer'],'retry gateway exists');
select has_function('app_private','complete_export_artifact_scan_job_v1',array['uuid','uuid','text','text','text','text','text','timestamp with time zone'],'completion gateway exists');
select has_function('customer_api','get_export_artifact_scan_status_v1',array['uuid','uuid','text','text'],'safe customer status gateway exists');
select ok(has_function_privilege('service_role','app_private.claim_export_artifact_scan_job_v1(text,text,integer)','EXECUTE'),'service worker may claim a job');
select ok(has_function_privilege('service_role','app_private.fail_export_artifact_scan_job_v1(uuid,uuid,text,integer)','EXECUTE'),'service worker may record transport failure');
select ok(has_function_privilege('service_role','app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamp with time zone)','EXECUTE'),'service worker may complete a job');
select ok(not has_function_privilege('authenticated','app_private.claim_export_artifact_scan_job_v1(text,text,integer)','EXECUTE'),'customer cannot claim a job');
select ok(not has_function_privilege('authenticated','app_private.fail_export_artifact_scan_job_v1(uuid,uuid,text,integer)','EXECUTE'),'customer cannot control retry state');
select ok(not has_function_privilege('authenticated','app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamp with time zone)','EXECUTE'),'customer cannot complete a scan');
select ok(has_function_privilege('authenticated','customer_api.get_export_artifact_scan_status_v1(uuid,uuid,text,text)','EXECUTE'),'customer may read authorized safe status');
select ok(not has_function_privilege('anon','customer_api.get_export_artifact_scan_status_v1(uuid,uuid,text,text)','EXECUTE'),'anonymous status access is denied');
select ok(position('skip locked' in lower(pg_get_functiondef('app_private.claim_export_artifact_scan_job_v1(text,text,integer)'::regprocedure)))>0,'concurrent workers use skip locked');
select ok(position('storage.objects' in pg_get_functiondef('app_private.claim_export_artifact_scan_job_v1(text,text,integer)'::regprocedure))>0,'job cannot lease before object exists');
select ok(position('export-artifact-vault' in pg_get_functiondef('app_private.claim_export_artifact_scan_job_v1(text,text,integer)'::regprocedure))>0,'claim is bound to private export vault');
select ok(position('scanning_pending' in pg_get_functiondef('app_private.claim_export_artifact_scan_job_v1(text,text,integer)'::regprocedure))>0,'only pending artifacts can be claimed');
select ok(position('attempt_count<q.max_attempts' in replace(pg_get_functiondef('app_private.claim_export_artifact_scan_job_v1(text,text,integer)'::regprocedure),' ',''))>0,'attempt ceiling blocks further leases');
select ok(position('lease_until<=statement_timestamp()' in replace(pg_get_functiondef('app_private.claim_export_artifact_scan_job_v1(text,text,integer)'::regprocedure),' ',''))>0,'expired lease is recoverable');
select ok(position('make_interval' in pg_get_functiondef('app_private.claim_export_artifact_scan_job_v1(text,text,integer)'::regprocedure))>0,'lease duration is bounded server-side');
select ok(position('dead_letter' in pg_get_functiondef('app_private.fail_export_artifact_scan_job_v1(uuid,uuid,text,integer)'::regprocedure))>0,'exhausted retry enters dead letter');
select ok(position('export_scan_job_lease_invalid' in pg_get_functiondef('app_private.fail_export_artifact_scan_job_v1(uuid,uuid,text,integer)'::regprocedure))>0,'failure requires current lease token');
select ok(position('export_scan_job_lease_invalid' in pg_get_functiondef('app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamptz)'::regprocedure))>0,'completion requires current lease token');
select ok(position('record_export_artifact_scan_v1' in pg_get_functiondef('app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamptz)'::regprocedure))>0,'completion reuses canonical scanner gate');
select ok(position('p_content_sha256' in pg_get_functiondef('app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamptz)'::regprocedure))>0,'completion carries content hash evidence');
select ok(position('p_signature' in pg_get_functiondef('app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamptz)'::regprocedure))>0,'completion carries signed attestation');
select ok(position('state=''completed''' in replace(pg_get_functiondef('app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamptz)'::regprocedure),' ',''))>0,'successful completion closes the job');
select ok(position('idempotent_replay' in pg_get_functiondef('app_private.complete_export_artifact_scan_job_v1(uuid,uuid,text,text,text,text,text,timestamptz)'::regprocedure))>0,'completed job retry is deterministic');
select ok(position('export_pack_actor_v1' in pg_get_functiondef('app_private.get_export_artifact_scan_status_internal_v1(uuid,uuid,text,text)'::regprocedure))>0,'status lookup preserves tenant authorization');
select ok(position('last_error_code' in pg_get_functiondef('app_private.fail_export_artifact_scan_job_v1(uuid,uuid,text,integer)'::regprocedure))>0,'sanitized failure code is retained');
select ok(position('last_error_code' in pg_get_functiondef('app_private.get_export_artifact_scan_status_internal_v1(uuid,uuid,text,text)'::regprocedure))=0,'customer status does not expose internal failure detail');
select ok(position('object_path' in pg_get_functiondef('app_private.get_export_artifact_scan_status_internal_v1(uuid,uuid,text,text)'::regprocedure))=0,'customer status does not expose private object path');
select ok(position('scan_status=''clean''' in replace(pg_get_functiondef('app_private.export_artifact_storage_allowed_v1(text,text)'::regprocedure),' ',''))>0,'download remains clean-only');
select ok(not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd in ('UPDATE','DELETE') and (coalesce(qual,'')||coalesce(with_check,'')) like '%export-artifact-vault%'),'customer cannot replace or delete vault objects');
select * from finish();
rollback;
