begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(15);
create temp table asset_guard_fixture as select gen_random_uuid() as tenant_a,gen_random_uuid() as tenant_b,gen_random_uuid() as user_id,gen_random_uuid() as prop_a,gen_random_uuid() as prop_other,gen_random_uuid() as prop_b,gen_random_uuid() as cat_a,gen_random_uuid() as cat_b,gen_random_uuid() as membership_id,gen_random_uuid() as context_id,gen_random_uuid() as building_a,gen_random_uuid() as building_other,gen_random_uuid() as unit_a,gen_random_uuid() as unit_other;
insert into auth.users(id,email) select user_id,'asset-guard-142@test.local' from asset_guard_fixture;
insert into platform.tenants(id,legal_name,registration_number,status) select tenant_a,'Asset guard A','ASSET-GUARD-142-A','active'::platform.record_status from asset_guard_fixture union all select tenant_b,'Asset guard B','ASSET-GUARD-142-B','active'::platform.record_status from asset_guard_fixture;
insert into portfolio.properties(id,tenant_id,type,name) select prop_a,tenant_a,'condominium'::portfolio.property_type,'Allowed' from asset_guard_fixture union all select prop_other,tenant_a,'condominium'::portfolio.property_type,'Other property' from asset_guard_fixture union all select prop_b,tenant_b,'condominium'::portfolio.property_type,'Other tenant' from asset_guard_fixture;
insert into assets.asset_categories(id,tenant_id,code,name,status) select cat_a,tenant_a,'PILOT','Pilot','active'::platform.record_status from asset_guard_fixture union all select cat_b,tenant_b,'PILOT','Pilot B','active'::platform.record_status from asset_guard_fixture;
insert into portfolio.buildings(id,tenant_id,property_id,code,name) select building_a,tenant_a,prop_a,'A','A' from asset_guard_fixture union all select building_other,tenant_a,prop_a,'B','B' from asset_guard_fixture;
insert into portfolio.units(id,tenant_id,building_id,code) select unit_a,tenant_a,building_a,'A1' from asset_guard_fixture union all select unit_other,tenant_a,building_a,'A2' from asset_guard_fixture;
insert into identity.memberships(id,tenant_id,user_id,role_id,status) select membership_id,tenant_a,user_id,(select id from identity.roles where code='property_manager' and tenant_id is null),'active' from asset_guard_fixture;
insert into identity.context_grants(id,membership_id,tenant_id,scope_type,property_id) select context_id,membership_id,tenant_a,'property',prop_a from asset_guard_fixture;
select set_config('request.jwt.claims',jsonb_build_object('sub',user_id,'role','authenticated','aal','aal1')::text,true) from asset_guard_fixture;
select lives_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-ALLOWED','Allowed asset'),'authorized own-property creation works') from asset_guard_fixture;
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_other,cat_a,'GUARD-DENIED','Denied asset'),'42501','asset_context_scope_violation','same-tenant other property is denied') from asset_guard_fixture;
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_b,cat_a,'GUARD-DENIED','Denied asset'),'22023','asset_entity_scope_invalid','cross-tenant property is denied') from asset_guard_fixture;
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_a,cat_b,'GUARD-DENIED','Denied asset'),'22023','asset_entity_scope_invalid','cross-tenant category is denied') from asset_guard_fixture;
update identity.context_grants set scope_type='building',building_id=(select building_a from asset_guard_fixture) where id=(select context_id from asset_guard_fixture);
select lives_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-BUILDING','Allowed building','building',building_a),'building context creates inside its building') from asset_guard_fixture;
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-DENIED','Other building','building',building_other),'42501','asset_context_scope_violation','another building in same property is denied') from asset_guard_fixture;
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-DENIED','Property asset'),'42501','asset_context_scope_violation','building context cannot create a property-wide asset') from asset_guard_fixture;
update identity.context_grants set scope_type='unit',unit_id=(select unit_a from asset_guard_fixture) where id=(select context_id from asset_guard_fixture);
select lives_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-UNIT','Allowed unit','unit',building_a,unit_a),'unit context creates inside its unit') from asset_guard_fixture;
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-DENIED','Other unit','unit',building_a,unit_other),'42501','asset_context_scope_violation','another unit in same building is denied') from asset_guard_fixture;
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-DENIED','Building asset','building',building_a),'42501','asset_context_scope_violation','unit context cannot create a building-wide asset') from asset_guard_fixture;
update identity.context_grants set scope_type='property',building_id=null,unit_id=null where id=(select context_id from asset_guard_fixture);
update identity.context_grants set starts_at=statement_timestamp()-interval '2 days',ends_at=statement_timestamp()-interval '1 day' where id=(select context_id from asset_guard_fixture);
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-DENIED','Denied asset'),'42501','asset_context_access_denied','expired context is denied') from asset_guard_fixture;
update identity.context_grants set ends_at=null,starts_at=statement_timestamp()+interval '1 day' where id=(select context_id from asset_guard_fixture);
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-DENIED','Denied asset'),'42501','asset_context_access_denied','future context is denied') from asset_guard_fixture;
update identity.context_grants set starts_at=statement_timestamp() where id=(select context_id from asset_guard_fixture);
update identity.memberships set starts_at=statement_timestamp()-interval '2 days',ends_at=statement_timestamp()-interval '1 day' where id=(select membership_id from asset_guard_fixture);
select throws_ok(format('select customer_api.create_asset_v1(%L,%L,%L,%L,%L)',context_id,prop_a,cat_a,'GUARD-DENIED','Denied asset'),'42501','asset_context_access_denied','expired membership is denied') from asset_guard_fixture;
select is((select count(*) from assets.assets where tenant_id=(select tenant_a from asset_guard_fixture)),3::bigint,'denied attempts created no assets');
select is((select count(*) from assets.asset_history where tenant_id=(select tenant_a from asset_guard_fixture)),3::bigint,'only allowed creation wrote history');
select * from finish();
rollback;
