begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(17);
create temp table asset_guard_fixture as select gen_random_uuid() as tenant_a,gen_random_uuid() as tenant_b,gen_random_uuid() as user_id,gen_random_uuid() as prop_a,gen_random_uuid() as prop_other,gen_random_uuid() as prop_b,gen_random_uuid() as cat_a,gen_random_uuid() as cat_b,gen_random_uuid() as membership_id,gen_random_uuid() as context_id,gen_random_uuid() as building_a,gen_random_uuid() as building_other,gen_random_uuid() as unit_a,gen_random_uuid() as unit_other;
insert into auth.users(id,email) select user_id,'asset-guard-142@test.local' from asset_guard_fixture;
insert into platform.tenants(id,legal_name,registration_number,status) select tenant_a,'Asset guard A','ASSET-GUARD-142-A','active'::platform.record_status from asset_guard_fixture union all select tenant_b,'Asset guard B','ASSET-GUARD-142-B','active'::platform.record_status from asset_guard_fixture;
insert into portfolio.properties(id,tenant_id,type,name) select prop_a,tenant_a,'condominium'::portfolio.property_type,'Allowed' from asset_guard_fixture union all select prop_other,tenant_a,'condominium'::portfolio.property_type,'Other property' from asset_guard_fixture union all select prop_b,tenant_b,'condominium'::portfolio.property_type,'Other tenant' from asset_guard_fixture;
insert into assets.asset_categories(id,tenant_id,code,name,status) select cat_a,tenant_a,'PILOT','Pilot','active'::platform.record_status from asset_guard_fixture union all select cat_b,tenant_b,'PILOT','Pilot B','active'::platform.record_status from asset_guard_fixture;
insert into portfolio.buildings(id,tenant_id,property_id,code,name) select building_a,tenant_a,prop_a,'A','A' from asset_guard_fixture union all select building_other,tenant_a,prop_a,'B','B' from asset_guard_fixture;
insert into portfolio.units(id,tenant_id,building_id,code) select unit_a,tenant_a,building_a,'A1' from asset_guard_fixture union all select unit_other,tenant_a,building_a,'A2' from asset_guard_fixture;
insert into identity.memberships(id,tenant_id,user_id,role_id,status) select membership_id,tenant_a,user_id,(select id from identity.roles where code='property_manager' and tenant_id is null),'active' from asset_guard_fixture;
insert into identity.context_grants(id,membership_id,tenant_id,scope_type,property_id) select context_id,membership_id,tenant_a,'property',prop_a from asset_guard_fixture;
select set_config('request.jwt.claims',jsonb_build_object('sub',user_id,'role','authenticated','aal','aal1')::text,true) from asset_guard_fixture;

update portfolio.properties set status='active' where tenant_id in (select tenant_a from asset_guard_fixture union all select tenant_b from asset_guard_fixture);
select is(jsonb_array_length(customer_api.get_asset_registration_choices_v1(context_id)->'properties'),1,'choices expose only the authorized property') from asset_guard_fixture;
select is(jsonb_array_length(customer_api.get_asset_registration_choices_v1(context_id)->'buildings'),2,'choices expose buildings in the authorized property') from asset_guard_fixture;
select lives_ok(format('select customer_api.register_equipment_v1(%L,%L,null,%L,%L,%L)',context_id,prop_a,'ventilation','REGISTER-143','Pilot ventilation'),'authorized noncritical registration works') from asset_guard_fixture;
select is((select count(*) from assets.assets where tenant_id=(select tenant_a from asset_guard_fixture)),1::bigint,'registration creates one asset');
select is((select count(*) from assets.asset_categories where tenant_id=(select tenant_a from asset_guard_fixture) and code='ventilation'),1::bigint,'missing category is created within the tenant');
select is((select count(*) from audit.events where tenant_id=(select tenant_a from asset_guard_fixture) and action='ASSET_CATEGORY_CREATED'),1::bigint,'category creation is audited');
select is((select count(*) from assets.asset_history where tenant_id=(select tenant_a from asset_guard_fixture)),1::bigint,'asset creation is audited');
select throws_ok(format('select customer_api.register_equipment_v1(%L,%L,null,%L,%L,%L)',context_id,prop_other,'other','DENIED-143','Denied'),'42501',null,'same-tenant other property remains forbidden') from asset_guard_fixture;
select is((select count(*) from assets.asset_categories where tenant_id=(select tenant_a from asset_guard_fixture) and code='other'),0::bigint,'rejected registration rolls category creation back');
select throws_ok(format('select customer_api.register_equipment_v1(%L,%L,null,%L,%L,%L)',context_id,prop_b,'pump','DENIED-143','Denied'),'22023',null,'foreign property is forbidden') from asset_guard_fixture;
select throws_ok(format('select customer_api.register_equipment_v1(%L,%L,null,%L,%L,%L)',context_id,prop_a,'ventilation','REGISTER-143','Duplicate'),'23505',null,'inventory code prevents duplicate creation') from asset_guard_fixture;
select throws_ok(format('select customer_api.register_equipment_v1(%L,%L,null,%L,%L,%L)',context_id,prop_a,'elevator','CRITICAL-143','Critical'),'42501',null,'critical equipment requires MFA') from asset_guard_fixture;
select is((select count(*) from assets.asset_categories where tenant_id=(select tenant_a from asset_guard_fixture) and code='elevator'),0::bigint,'MFA denial rolls category creation back');
update identity.context_grants set starts_at=statement_timestamp()-interval '2 days',ends_at=statement_timestamp()-interval '1 day' where id=(select context_id from asset_guard_fixture);
select throws_ok(format('select customer_api.get_asset_registration_choices_v1(%L)',context_id),'42501',null,'expired context cannot load registration choices') from asset_guard_fixture;
select throws_ok(format('select customer_api.register_equipment_v1(%L,%L,null,%L,%L,%L)',context_id,prop_a,'ventilation','EXPIRED-143','Expired'),'42501',null,'expired context cannot register equipment') from asset_guard_fixture;
select ok(not has_function_privilege('anon','customer_api.register_equipment_v1(uuid,uuid,uuid,text,text,text)','EXECUTE'),'anonymous callers cannot register equipment');
select ok(not has_function_privilege('authenticated','assets.registration_context_v1(uuid)','EXECUTE'),'private authority helper is not directly executable by authenticated callers');
select * from finish();
rollback;
