begin;
set local search_path=public,extensions;
select plan(18);
select has_table('occupancy','lease_handover_receipts','T07 handover receipts exist');
select has_table('occupancy','lease_termination_receipts','T07 termination receipts exist');
select has_function('customer_api','execute_verified_lease_handover_v1',array['uuid','uuid','uuid','uuid','uuid','uuid','text','jsonb','jsonb','text'],'activation command exists');
select has_function('customer_api','terminate_verified_lease_v1',array['uuid','uuid','uuid','uuid','date','date','uuid[]','text','text'],'termination command exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='occupancy' and c.relname='lease_handover_receipts'),'handover receipts use RLS');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='occupancy' and c.relname='lease_termination_receipts'),'termination receipts use RLS');
select is((select count(*)::int from information_schema.role_table_grants where table_schema='occupancy' and table_name='lease_handover_receipts' and grantee in('anon','authenticated','service_role')),0,'no direct handover grants');
select is((select count(*)::int from information_schema.role_table_grants where table_schema='occupancy' and table_name='lease_termination_receipts' and grantee in('anon','authenticated','service_role')),0,'no direct termination grants');
select ok(has_function_privilege('authenticated','customer_api.execute_verified_lease_handover_v1(uuid,uuid,uuid,uuid,uuid,uuid,text,jsonb,jsonb,text)','EXECUTE') and not has_function_privilege('anon','customer_api.execute_verified_lease_handover_v1(uuid,uuid,uuid,uuid,uuid,uuid,text,jsonb,jsonb,text)','EXECUTE'),'authenticated alone executes activation');
select ok(has_function_privilege('authenticated','customer_api.terminate_verified_lease_v1(uuid,uuid,uuid,uuid,date,date,uuid[],text,text)','EXECUTE') and not has_function_privilege('anon','customer_api.terminate_verified_lease_v1(uuid,uuid,uuid,uuid,date,date,uuid[],text,text)','EXECUTE'),'authenticated alone executes termination');
select isnt((select prosecdef from pg_proc where oid='customer_api.execute_verified_lease_handover_v1(uuid,uuid,uuid,uuid,uuid,uuid,text,jsonb,jsonb,text)'::regprocedure),false,'activation is a guarded definer gateway');
select isnt((select prosecdef from pg_proc where oid='customer_api.terminate_verified_lease_v1(uuid,uuid,uuid,uuid,date,date,uuid[],text,text)'::regprocedure),false,'termination is a guarded definer gateway');
select is((select count(*)::int from identity.permissions where code='core.relationships.lease'),1,'lease permission is unique');
select is((select count(*)::int from platform.module_permission_bindings b join identity.permissions p on p.id=b.permission_id where p.code='core.relationships.lease' and b.lifecycle_status='active' and b.requires_aal2 and not b.is_delegable),1,'lease permission has one AAL2 nondelegable binding');
select ok(exists(select 1 from pg_constraint c where c.conrelid='occupancy.lease_handover_receipts'::regclass and c.contype='f' and pg_get_constraintdef(c.oid) like 'FOREIGN KEY (lease_id)%'),'handover lease is constrained');
select ok(exists(select 1 from pg_constraint c where c.conrelid='occupancy.lease_handover_receipts'::regclass and c.contype='f' and pg_get_constraintdef(c.oid) like 'FOREIGN KEY (evidence_version_id)%'),'handover evidence is constrained');
select ok(exists(select 1 from pg_constraint c where c.conrelid='occupancy.lease_termination_receipts'::regclass and c.contype='f' and pg_get_constraintdef(c.oid) like 'FOREIGN KEY (lease_id)%'),'termination lease is constrained');
select is((select count(*)::int from occupancy.lease_handover_receipts)+(select count(*)::int from occupancy.lease_termination_receipts),0,'migration creates no business receipts');
select * from finish();
rollback;
