'use client';
import {useState} from 'react';
import {CORES,requirement,roleUse,REGISTRY_VERSION} from '@/lib/module-registry/registry';
import {PROPERTY_PROFILES,OPERATING_MODELS,PROFILE_MODEL_COMPATIBILITY} from '@/lib/module-registry/taxonomy';
import {LAB_ROLES,labRoleName} from '@/lib/dashboard-lab/catalog';
import type {Language} from '@/types';
const copy={
 fa:{title:'نگاشت ۱۷ هسته و نیاز ورک‌اسپیس',intro:'نسخهٔ مصوب برنامه‌ریزی محصول؛ این جدول مجوز دسترسی ایجاد نمی‌کند و وضعیت نصب زنده نیست. فعال‌سازی واقعی به سازگاری، اشتراک، نقش و محدوده وابسته است.',profile:'نوع ملک',model:'مدل بهره‌برداری',role:'نقش آزمایشی',core:'هسته',need:'نیاز پیشنهادی',use:'کاربرد نقش',status:'وضعیت پیاده‌سازی',mapping:'ماژول اجرایی / مسیر',gap:'فاصله تا تکمیل',recommended:'پیشنهاد فعال',optional:'اختیاری',off:'پیش‌فرض خاموش؛ قابل انتخاب',manage:'مدیریت در محدوده مجاز',review:'نظارت / تأیید در حدود مجوز',own:'فقط اطلاعات و وظایف خود',internal:'مدیریت پلتفرم؛ بدون دسترسی خودکار مشتری',none:'بدون کاربرد مستقیم',operational_slice:'گردش‌کار پایه پیاده‌شده',partial:'بخشی پیاده‌شده',read_model:'نمای فقط‌خواندنی',planned:'برنامه‌ریزی‌شده',compatible:'ترکیب سازگار',review_required:'ترکیب نیازمند بررسی',incompatible:'ترکیب ناسازگار؛ قابل فعال‌سازی نیست',unmapped:'ماژول مستقل قابل نصب ندارد',note:'هدف محصول: عرضه هر ۱۷ هسته برای همه ورک‌اسپیس‌ها؛ موارد برنامه‌ریزی‌شده هنوز قابل فعال‌سازی نیستند. پیشنهاد فعال الزام قانونی نیست. امنیت پایه همیشه فعال می‌ماند؛ خاموش‌کردن قابلیت‌ها سوابق را حذف نمی‌کند. نیاز تجهیز و قرارداد در مرحله آماده‌سازی ملک تأیید می‌شود. نقش سفارشی باید جدا با مجوزهای واقعی آزموده شود.',maintenance:'نگهداری دوره‌ای: C07 تجهیز ← C09 برنامه و دستورکار ← C10 پیمانکار و قرارداد. فاصله سرویس از قرارداد و مشخصات تجهیز تعیین می‌شود؛ عدد قانونی پیش‌فرض نداریم.'},
 ro:{title:'Harta celor 17 nuclee și necesarul spațiului',intro:'Referință versionată de planificare; nu acordă permisiuni și nu reprezintă instalările live. Activarea depinde de compatibilitate, abonament, rol și domeniu.',profile:'Profil imobiliar',model:'Model operațional',role:'Rol de test',core:'Nucleu',need:'Necesar recomandat',use:'Utilizare rol',status:'Implementare',mapping:'Modul executabil / rută',gap:'Ce rămâne',recommended:'Recomandat activ',optional:'Opțional',off:'Implicit oprit; selectabil',manage:'Administrare în domeniul autorizat',review:'Supraveghere / aprobare autorizată',own:'Doar date și sarcini proprii',internal:'Administrarea platformei; fără acces automat la clienți',none:'Fără utilizare directă',operational_slice:'Flux de bază implementat',partial:'Parțial implementat',read_model:'Vizualizare doar pentru citire',planned:'Planificat',compatible:'Combinație compatibilă',review_required:'Necesită revizuire',incompatible:'Combinație incompatibilă; activare blocată',unmapped:'Fără modul instalabil separat',note:'Ținta produsului: toate cele 17 nuclee pentru fiecare spațiu; cele planificate nu pot fi activate încă. Recomandarea nu este o obligație legală. Securitatea de bază rămâne activă; dezactivarea nu șterge istoricul. Echipamentele și contractele se confirmă la pregătirea proprietății. Rolurile personalizate necesită teste separate ale permisiunilor reale.',maintenance:'Mentenanță periodică: C07 activ → C09 plan și comandă → C10 furnizor și contract. Intervalul provine din contract și specificații; nu există interval legal implicit.'},
 en:{title:'17-core map and workspace requirements',intro:'Versioned product planning reference; it grants no access and is not live installation state. Activation depends on compatibility, subscription, role and scope.',profile:'Property profile',model:'Operating model',role:'Test role',core:'Core',need:'Recommended need',use:'Role use',status:'Implementation',mapping:'Runtime module / route',gap:'Remaining gap',recommended:'Recommended on',optional:'Optional',off:'Default off; selectable',manage:'Manage within authorized scope',review:'Authorized oversight / approval',own:'Own records and tasks only',internal:'Platform administration; no automatic customer access',none:'No direct use',operational_slice:'Core workflow implemented',partial:'Partially implemented',read_model:'Read-only view',planned:'Planned',compatible:'Compatible combination',review_required:'Review required',incompatible:'Incompatible combination; activation blocked',unmapped:'No separate installable module',note:'Product target: all 17 cores for every workspace; planned cores cannot be activated yet. Recommendations are not legal obligations. Core security stays on; deactivation preserves records. Equipment and contract needs are confirmed during property preparation. Custom roles need separate testing with their real permissions.',maintenance:'Recurring maintenance: C07 asset → C09 plan and work order → C10 vendor and contract. Intervals come from the contract and equipment specifications; there is no default legal interval.'},
};
export function ModuleRegistryPanel({lang}:{lang:Language}){
 const t=copy[lang];const [profile,setProfile]=useState<string>(PROPERTY_PROFILES[0].code),[model,setModel]=useState<string>(OPERATING_MODELS[0].code),[role,setRole]=useState<string>(LAB_ROLES[0]);
 const compatibility=PROFILE_MODEL_COMPATIBILITY[`${profile}:${model}`]??'incompatible';
 return <section dir={lang==='fa'?'rtl':'ltr'} className="space-y-5 text-slate-900"><header className="rounded-2xl bg-white p-5"><h1 className="text-2xl font-bold">{t.title}</h1><p className="mt-2">{t.intro}</p><p className="mt-2 text-xs">{REGISTRY_VERSION}</p></header><div className="grid gap-4 rounded-2xl bg-white p-5 md:grid-cols-3"><label>{t.profile}<select className="mt-2 w-full rounded border p-2" value={profile} onChange={e=>setProfile(e.target.value)}>{PROPERTY_PROFILES.map(p=><option key={p.code} value={p.code}>{p.labels[lang]}</option>)}</select></label><label>{t.model}<select className="mt-2 w-full rounded border p-2" value={model} onChange={e=>setModel(e.target.value)}>{OPERATING_MODELS.map(m=><option key={m.code} value={m.code}>{m.labels[lang]}</option>)}</select></label><label>{t.role}<select className="mt-2 w-full rounded border p-2" value={role} onChange={e=>setRole(e.target.value)}>{LAB_ROLES.map(r=><option key={r} value={r}>{labRoleName(r,lang)}</option>)}</select></label><p role="status" className="md:col-span-3">{t[compatibility as 'compatible'|'review_required'|'incompatible']}</p></div><p className="rounded-xl bg-amber-50 p-4">{t.note}</p><p className="rounded-xl bg-teal-50 p-4">{t.maintenance}</p><div className="overflow-x-auto rounded-xl bg-white"><table className="w-full text-start text-sm"><thead><tr>{[t.core,t.need,t.use,t.status,t.mapping,t.gap].map(h=><th key={h} className="border-b p-3 text-start">{h}</th>)}</tr></thead><tbody>{CORES.map(c=><tr key={c.code}><th className="border-b p-3 text-start"><span dir="ltr">{c.code}</span><br/>{c.name[lang]}</th><td className="border-b p-3">{compatibility==='incompatible'?'—':t[requirement(c.code,profile,model)]}</td><td className="border-b p-3">{t[roleUse(c.code,role)]}</td><td className="border-b p-3">{t[c.status]}</td><td className="border-b p-3"><div dir="ltr">{c.modules.join(', ')||t.unmapped}</div>{c.routes.map(r=><div key={r} dir="ltr" className="mt-1 text-xs">/app/{r}</div>)}</td><td className="min-w-56 border-b p-3">{c.gap[lang]}</td></tr>)}</tbody></table></div></section>;
}
