'use client';

import { useCallback, useState } from 'react';
import { Check, GitCompareArrows, RefreshCw, X } from 'lucide-react';
import type { Language } from '@/types';
import { useCustomerContext } from './CustomerContextProvider';

type QueueItem={item_type:'suggestion'|'exception';id:string;bank_transaction_id:string;status:string;matched_amount:number|null;confidence:number|null;details:Record<string,unknown>};
const text={
  ro:{open:'Potrivire asistată',title:'Coadă de potrivire și excepții',run:'Generează propuneri',approve:'Aprobă',reject:'Respinge',empty:'Nu există propuneri sau excepții deschise.',close:'Închide',suggestion:'Propunere',exception:'Excepție',dual:'Propunerile necesită aprobare independentă AAL2.'},
  en:{open:'Assisted matching',title:'Matching and exception queue',run:'Generate suggestions',approve:'Approve',reject:'Reject',empty:'No open suggestions or exceptions.',close:'Close',suggestion:'Suggestion',exception:'Exception',dual:'Suggestions require independent AAL2 approval.'},
  fa:{open:'تطبیق هدایت‌شده',title:'صف تطبیق و مغایرت‌های بانکی',run:'تولید پیشنهادها',approve:'تأیید',reject:'رد',empty:'پیشنهاد یا مغایرت بازی وجود ندارد.',close:'بستن',suggestion:'پیشنهاد',exception:'مغایرت',dual:'پیشنهادها به تأیید مستقل AAL2 نیاز دارند.'},
};

export function BankMatchingWorkQueue({lang,bankAccountId,onChanged}:{lang:Language;bankAccountId?:string;onChanged:()=>void}){
  const {active}=useCustomerContext();const t=text[lang];const [open,setOpen]=useState(false);const [items,setItems]=useState<QueueItem[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!active)return;setBusy(true);setError(null);try{const q=new URLSearchParams({context_id:active.context_id,limit:'100'});if(bankAccountId)q.set('bank_account_id',bankAccountId);const r=await fetch(`/api/customer/v1/payments/bank-matching?${q}`,{cache:'no-store',credentials:'same-origin'});const b=await r.json();if(!r.ok)throw new Error(b?.error?.code??'QUEUE_FAILED');setItems(b.items??[]);}catch(reason){setError(reason instanceof Error?reason.message:'QUEUE_FAILED');}finally{setBusy(false);}},[active,bankAccountId]);
  async function generate(){if(!active||!bankAccountId)return;const now=new Date();const end=now.toISOString().slice(0,10);const start=`${end.slice(0,8)}01`;setBusy(true);setError(null);try{const r=await fetch('/api/customer/v1/payments/bank-matching',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({context_id:active.context_id,bank_account_id:bankAccountId,period_start:start,period_end:end,idempotency_key:crypto.randomUUID()})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.code??'MATCH_RUN_FAILED');await load();onChanged();}catch(reason){setError(reason instanceof Error?reason.message:'MATCH_RUN_FAILED');}finally{setBusy(false);}}
  async function review(id:string,decision:'approve'|'reject'){if(!active)return;setBusy(true);setError(null);try{const r=await fetch(`/api/customer/v1/payments/bank-matching/matches/${id}/review`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({context_id:active.context_id,decision,reason:decision==='reject'?'Rejected during controlled review':null})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.code??'REVIEW_FAILED');await load();onChanged();}catch(reason){setError(reason instanceof Error?reason.message:'REVIEW_FAILED');}finally{setBusy(false);}}
  return <>
    <button type="button" disabled={!bankAccountId} onClick={()=>{setOpen(true);void load();}} className="inline-flex items-center gap-1.5 rounded-xl border border-[#0E9F8E] bg-white px-4 py-2 text-sm font-bold text-[#0E9F8E] disabled:opacity-50"><GitCompareArrows className="h-4 w-4"/>{t.open}</button>
    {open?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-modal="true" aria-labelledby="bank-matching-title" className="max-h-[85vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl" dir={lang==='fa'?'rtl':'ltr'}>
      <div className="flex items-start justify-between gap-4"><div><h2 id="bank-matching-title" className="text-lg font-black text-[#0F172A]">{t.title}</h2><p className="mt-1 text-xs text-[#52667A]">{t.dual}</p></div><button type="button" aria-label={t.close} onClick={()=>setOpen(false)} className="rounded-lg border p-2"><X className="h-4 w-4"/></button></div>
      <div className="mt-4 flex gap-2"><button type="button" disabled={busy} onClick={generate} className="rounded-xl bg-[#0E9F8E] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{t.run}</button><button type="button" disabled={busy} onClick={()=>void load()} aria-label="Refresh matching queue" className="rounded-xl border p-2"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/></button></div>
      {error?<p role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>:null}
      <div className="mt-4 space-y-2">{items.length===0&&!busy?<p className="rounded-xl bg-slate-50 p-4 text-sm text-[#52667A]">{t.empty}</p>:items.map(item=><article key={`${item.item_type}-${item.id}`} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.item_type==='suggestion'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{item.item_type==='suggestion'?t.suggestion:t.exception}</span><p className="mt-2 font-mono text-xs text-[#52667A]">{item.bank_transaction_id}</p><p className="mt-1 text-sm font-bold">{item.matched_amount??'—'} {item.confidence===null?'':`· ${Math.round(item.confidence*100)}%`}</p></div>{item.item_type==='suggestion'?<div className="flex gap-2"><button type="button" disabled={busy} onClick={()=>review(item.id,'approve')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><Check className="h-3.5 w-3.5"/>{t.approve}</button><button type="button" disabled={busy} onClick={()=>review(item.id,'reject')} className="inline-flex items-center gap-1 rounded-lg border border-rose-300 px-3 py-2 text-xs font-bold text-rose-700"><X className="h-3.5 w-3.5"/>{t.reject}</button></div>:null}</div></article>)}</div>
    </section></div>:null}
  </>;
}
