"use client";
import {useEffect,useMemo,useState} from "react";
import {useCustomerContext} from "./CustomerContextProvider";
type Lang="ro"|"en"|"fa";type Unit={code:string;floor:string;area:string};type Stage="edit"|"draft"|"rehearsed"|"submitted"|"approved"|"provisioned";
const copy={
 ro:{title:"Configurare controlată a clădirii",body:"Definiți structura și simulați soldurile de deschidere înainte de orice scriere.",association:"Asociație",building:"Clădire",code:"Cod",floors:"Etaje",period:"Perioadă contabilă",units:"Unități",add:"Adaugă unitate",area:"Suprafață m²",debit:"Solduri debit",credit:"Solduri credit",preview:"Previzualizare",actions:["Creează proiect","Rulează simularea","Trimite spre aprobare","Aprobă independent","Creează structura"],save:"Salvează unitățile",saved:"Unități salvate",difference:"Diferență",context:"Selectați mai întâi un context de lucru.",notice:"Acceptanța folosește numai date sintetice. Aprobarea necesită un alt utilizator AAL2.",ok:"Operațiunea a fost înregistrată.",error:"Operațiunea a fost respinsă",remove:"Elimină"},
 en:{title:"Controlled building setup",body:"Define the structure and rehearse opening balances before any write.",association:"Association",building:"Building",code:"Code",floors:"Floors",period:"Accounting period",units:"Units",add:"Add unit",area:"Area m²",debit:"Opening debits",credit:"Opening credits",preview:"Preview",actions:["Create draft","Run rehearsal","Submit for approval","Approve independently","Provision structure"],save:"Save units",saved:"Saved units",difference:"Difference",context:"Select a working context first.",notice:"Use synthetic data only. Approval requires another AAL2 user.",ok:"The operation was recorded.",error:"The operation was rejected",remove:"Remove"},
 fa:{title:"راه‌اندازی کنترل‌شده ساختمان",body:"ساختار را تعریف و مانده افتتاحیه را پیش از هرگونه نوشتن آزمایش کنید.",association:"انجمن",building:"ساختمان",code:"کد",floors:"طبقات",period:"دوره حسابداری",units:"واحدها",add:"افزودن واحد",area:"مساحت مترمربع",debit:"مانده بدهکار",credit:"مانده بستانکار",preview:"پیش‌نمایش",actions:["ایجاد پیش‌نویس","اجرای آزمایشی","ارسال برای تأیید","تأیید مستقل","ایجاد ساختار"],save:"ذخیرهٔ واحدها",saved:"واحد ثبت‌شده",difference:"اختلاف",context:"ابتدا یک زمینه کاری انتخاب کنید.",notice:"فقط از داده مصنوعی استفاده کنید. تأیید به کاربر AAL2 دیگری نیاز دارد.",ok:"عملیات ثبت شد.",error:"عملیات رد شد",remove:"حذف"}};
export function CustomerBuildingSetupWizard({lang}:{lang:Lang}){
 const t=copy[lang],{active}=useCustomerContext();const[association,setAssociation]=useState("CLADORA Synthetic Association"),[building,setBuilding]=useState("Synthetic Building A"),[code,setCode]=useState("BLD-A"),[floors,setFloors]=useState("4"),[start,setStart]=useState("2026-01-01"),[end,setEnd]=useState("2026-12-31"),[units,setUnits]=useState<Unit[]>([{code:"A-01",floor:"0",area:"62"}]),[debit,setDebit]=useState("0"),[credit,setCredit]=useState("0"),[runId,setRunId]=useState(""),[stage,setStage]=useState<Stage>("edit"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [savedUnits,setSavedUnits]=useState<Unit[]|null>(null);
 const difference=useMemo(()=>Number(debit||0)-Number(credit||0),[debit,credit]),field="rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-teal-600 disabled:bg-slate-50";
 const dirtyUnits=stage==="draft"&&JSON.stringify(units)!==JSON.stringify(savedUnits);
 const wireUnits=()=>units.map(u=>({code:u.code,floor:u.floor===""?null:Number(u.floor),area_m2:u.area===""?null:Number(u.area)}));
 useEffect(()=>{if(!active?.context_id)return;const key=`building-setup:${active.context_id}`;const fromUrl=new URLSearchParams(window.location.search).get("run_id");const restored=fromUrl&&/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(fromUrl)?fromUrl:window.sessionStorage.getItem(key);if(!restored)return;const controller=new AbortController();fetch(`/api/customer/v1/onboarding/building-setup/${restored}?context_id=${active.context_id}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error?.code||"UNKNOWN");return result}).then(result=>{if(controller.signal.aborted)return;const payload=result.payload;const recorded=(result.effective_units??payload.units).map((u:{code:string;floor:number|null;area_m2:number|null})=>({code:u.code,floor:u.floor===null?"":String(u.floor),area:u.area_m2===null?"":String(u.area_m2)}));setRunId(result.run_id);setStage(result.status);setSavedUnits(recorded);setUnits(recorded);setAssociation(payload.association.name);setBuilding(payload.building.name);setCode(payload.building.code);setFloors(String(payload.building.floors));setStart(payload.period_start);setEnd(payload.period_end);setDebit(String(payload.opening_balances.filter((v:{side:string})=>v.side==="debit").reduce((sum:number,v:{amount:number})=>sum+v.amount,0)));setCredit(String(payload.opening_balances.filter((v:{side:string})=>v.side==="credit").reduce((sum:number,v:{amount:number})=>sum+v.amount,0)));window.sessionStorage.setItem(key,result.run_id)}).catch(error=>{if(!controller.signal.aborted)setMessage(String(error))});return()=>controller.abort()},[active?.context_id]);
 const updateUnit=(i:number,key:keyof Unit,value:string)=>setUnits((list)=>list.map((u,n)=>n===i?{...u,[key]:value}:u));
 async function call(action?:"rehearse"|"submit"|"provision"|"save") {
  if(!active?.context_id){setMessage(t.context);return}
  setBusy(true);setMessage("");
  try {
   if(stage==="draft"&&(action==="save"||(action==="rehearse"&&dirtyUnits))){
    const saved=await fetch(`/api/customer/v1/onboarding/building-setup/${runId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({context_id:active.context_id,units:wireUnits()})});
    const savedResult=await saved.json();if(!saved.ok)throw new Error(savedResult.error?.code||"UNKNOWN");setSavedUnits(units.map(unit=>({...unit})));
    if(action==="save"){setMessage(t.ok);return}
   }
   const payload={context_id:active.context_id,...(action?{}:{idempotency_key:`setup-${crypto.randomUUID()}`,payload:{association:{name:association},building:{name:building,code,floors:Number(floors)},currency:"RON",period_start:start,period_end:end,units:wireUnits(),opening_balances:[...(Number(debit)>0?[{account_code:"OPEN-DEBIT",side:"debit",amount:Number(debit)}]:[]),...(Number(credit)>0?[{account_code:"OPEN-CREDIT",side:"credit",amount:Number(credit)}]:[])]}})};
   const response=await fetch(action?`/api/customer/v1/onboarding/building-setup/${runId}/${action}`:"/api/customer/v1/onboarding/building-setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
   const result=await response.json();if(!response.ok)throw new Error(result.error?.code||"UNKNOWN");
   if(result.run_id){setRunId(result.run_id);if(!action)setSavedUnits(units.map(unit=>({...unit})));if(result.status==="provisioned")window.sessionStorage.removeItem(`building-setup:${active.context_id}`);else window.sessionStorage.setItem(`building-setup:${active.context_id}`,result.run_id)}
   if(result.status)setStage(result.status);setMessage(t.ok);
  }catch(error){setMessage(`${t.error}: ${error instanceof Error?error.message:"UNKNOWN"}`)}finally{setBusy(false)}
 }
 const actionDefs:[Stage,(()=>void)][]=[["edit",()=>call()],["draft",()=>call("rehearse")],["rehearsed",()=>call("submit")]];
 return <section dir={lang==="fa"?"rtl":"ltr"} className="mx-auto max-w-5xl space-y-6 rounded-2xl border bg-white p-6 shadow-sm"><header><p className="text-sm font-semibold text-teal-700">CLADORA-P2-SETUP-001 · Migration 94 · Test 081</p><h1 className="mt-2 text-2xl font-bold">{t.title}</h1><p className="mt-2 text-slate-600">{t.body}</p></header><p className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm">{t.notice}</p>
 <fieldset disabled={stage!=="edit"} className="grid gap-4 md:grid-cols-2">{[[t.association,association,setAssociation],[t.building,building,setBuilding],[t.code,code,setCode],[t.floors,floors,setFloors]].map(([label,value,setter])=><label key={label as string} className="grid gap-1 text-sm">{label as string}<input className={field} type={label===t.floors?"number":"text"} value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}</fieldset>
 <fieldset disabled={stage!=="edit"} className="grid gap-4 rounded-xl border p-4 md:grid-cols-2"><legend className="px-2 font-semibold">{t.period}</legend><input aria-label="period start" className={field} type="date" value={start} onChange={e=>setStart(e.target.value)}/><input aria-label="period end" className={field} type="date" value={end} onChange={e=>setEnd(e.target.value)}/></fieldset>
 <div className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">{t.units}{savedUnits?` · ${t.saved}: ${savedUnits.length}`:""}</h2><button type="button" disabled={stage!=="edit"&&stage!=="draft"} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40" onClick={()=>setUnits(u=>[...u,{code:`A-${String(u.length+1).padStart(2,"0")}`,floor:"",area:""}])}>{t.add}</button></div>{units.map((unit,i)=><div key={i} className="grid gap-2 sm:grid-cols-4"><input aria-label={`${t.code} ${i+1}`} disabled={stage!=="edit"&&stage!=="draft"} className={field} value={unit.code} onChange={e=>updateUnit(i,"code",e.target.value)}/><input aria-label={`${t.floors} ${i+1}`} disabled={stage!=="edit"&&stage!=="draft"} className={field} type="number" value={unit.floor} onChange={e=>updateUnit(i,"floor",e.target.value)}/><input aria-label={`${t.area} ${i+1}`} disabled={stage!=="edit"&&stage!=="draft"} className={field} type="number" min="0" step="0.01" value={unit.area} onChange={e=>updateUnit(i,"area",e.target.value)}/><button type="button" disabled={units.length===1||(stage!=="edit"&&stage!=="draft")} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40" onClick={()=>setUnits(u=>u.filter((_,n)=>n!==i))}>{t.remove}</button></div>)}</div>
 <fieldset disabled={stage!=="edit"} className="grid gap-4 rounded-xl border p-4 md:grid-cols-2"><legend className="px-2 font-semibold">{t.preview}</legend><label className="grid gap-1 text-sm">{t.debit}<input className={field} type="number" min="0" step="0.01" value={debit} onChange={e=>setDebit(e.target.value)}/></label><label className="grid gap-1 text-sm">{t.credit}<input className={field} type="number" min="0" step="0.01" value={credit} onChange={e=>setCredit(e.target.value)}/></label><p className={`md:col-span-2 rounded-lg p-3 text-sm font-semibold ${difference===0?"bg-teal-50 text-teal-800":"bg-red-50 text-red-700"}`}>{t.difference}: {difference.toFixed(2)} RON · {units.length} {t.units}</p></fieldset>
 {dirtyUnits&&<p className="text-sm font-semibold text-amber-800">{t.save}</p>}<div className="flex flex-wrap gap-2">{actionDefs.map(([required,handler],i)=><button key={required} disabled={busy||stage!==required||(required==="edit"&&difference!==0)} className="rounded-lg bg-teal-800 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" onClick={handler}>{t.actions[i]}</button>)}{stage==="draft"&&<button disabled={busy||!dirtyUnits} className="rounded-lg border border-teal-700 px-4 py-2 text-sm font-semibold text-teal-800 disabled:opacity-40" onClick={()=>call("save")}>{t.save}</button>}<button disabled={busy||!runId||!(["submitted","approved"] as Stage[]).includes(stage)} className="rounded-lg bg-teal-800 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" onClick={()=>call("provision")}>{t.actions[4]}</button></div><p aria-live="polite" className="text-sm text-slate-700">{stage.toUpperCase()}{runId?` · ${runId}`:""}{message?` · ${message}`:""}</p></section>}
