'use client';
import { useEffect, useId, useRef, useState } from 'react';
import type { Language } from '@/types';
import { CustomerAirpropDiligence } from './CustomerAirpropDiligence';
import { CustomerAirpropUnderwriting } from './CustomerAirpropUnderwriting';
import { useCustomerContext } from './CustomerContextProvider';
import { createAirpropOpportunityV2Schema } from '@/lib/airprop/opportunity-contract-v2';
import { managementPortfolioResponseV1Schema } from '@/lib/airprop/commercial-lifecycle-v1';

const copy = {
 en: { title: 'AIRPROP workspace', choose: 'Select workspace', empty: 'No authorized workspace is available in this context.', context: 'Select a context to continue.', error: 'Unable to load this workspace.', name: 'Opportunity name', city: 'City', price: 'Asking price', currency: 'Currency', create: 'Create opportunity', retry: 'Retry the same request', pending: 'The result is uncertain. Retry this request before creating another opportunity.', invalid: 'Check the name, city and positive price (up to four decimal places).', denied: 'This action is unavailable with your current access.', mfa: 'Verify your identity to continue.', nameError: 'Enter a name of 1–160 characters without control characters.', cityError: 'Enter a city of 1–120 characters without control characters.', priceError: 'Enter a positive price using a decimal point and up to four decimal places.', success: 'Opportunity saved.', opportunities: 'Opportunities', none: 'No opportunities yet.', loading: 'Loading…', status: 'Status', refresh: 'Refresh', draft: 'Draft', qualified: 'Qualified', underwriting: 'Underwriting', approved: 'Approved', rejected: 'Rejected', archived: 'Archived' },
 ro: { title: 'Workspace AIRPROP', choose: 'Selectează workspace-ul', empty: 'Nu există un workspace autorizat în acest context.', context: 'Selectează un context pentru a continua.', error: 'Workspace-ul nu poate fi încărcat.', name: 'Numele oportunității', city: 'Oraș', price: 'Preț solicitat', currency: 'Monedă', create: 'Creează oportunitatea', retry: 'Reîncearcă aceeași cerere', pending: 'Rezultatul este incert. Reîncearcă această cerere înainte de a crea altă oportunitate.', invalid: 'Verifică numele, orașul și prețul pozitiv (maximum patru zecimale).', denied: 'Acțiunea nu este disponibilă cu accesul actual.', mfa: 'Confirmă-ți identitatea pentru a continua.', nameError: 'Introdu un nume de 1–160 de caractere, fără caractere de control.', cityError: 'Introdu un oraș de 1–120 de caractere, fără caractere de control.', priceError: 'Introdu un preț pozitiv cu punct zecimal și maximum patru zecimale.', success: 'Oportunitate salvată.', opportunities: 'Oportunități', none: 'Nu există încă oportunități.', loading: 'Se încarcă…', status: 'Stare', refresh: 'Actualizează', draft: 'Ciornă', qualified: 'Calificată', underwriting: 'Analiză', approved: 'Aprobată', rejected: 'Respinsă', archived: 'Arhivată' },
 fa: { title: 'ورک‌اسپیس AIRPROP', choose: 'انتخاب ورک‌اسپیس', empty: 'در این زمینه، ورک‌اسپیس مجازی برای شما در دسترس نیست.', context: 'برای ادامه یک زمینهٔ دسترسی انتخاب کنید.', error: 'اطلاعات ورک‌اسپیس دریافت نشد.', name: 'نام فرصت', city: 'شهر', price: 'قیمت پیشنهادی', currency: 'ارز', create: 'ثبت فرصت', retry: 'تلاش مجدد برای همین درخواست', pending: 'نتیجهٔ درخواست مشخص نیست. پیش از ثبت فرصت دیگر، همین درخواست را دوباره ارسال کنید.', invalid: 'نام، شهر و قیمت مثبت با حداکثر چهار رقم اعشار را بررسی کنید.', denied: 'این اقدام با دسترسی فعلی شما مجاز نیست.', mfa: 'برای ادامه، هویت خود را تأیید کنید.', nameError: 'نامی بین ۱ تا ۱۶۰ نویسه و بدون نویسهٔ کنترلی وارد کنید.', cityError: 'نام شهر را بین ۱ تا ۱۲۰ نویسه و بدون نویسهٔ کنترلی وارد کنید.', priceError: 'قیمت مثبت را با نقطهٔ اعشار و حداکثر چهار رقم اعشار وارد کنید.', success: 'فرصت ثبت شد.', opportunities: 'فرصت‌ها', none: 'هنوز فرصتی ثبت نشده است.', loading: 'در حال دریافت…', status: 'وضعیت', refresh: 'تازه‌سازی', draft: 'پیش‌نویس', qualified: 'ارزیابی اولیه', underwriting: 'تحلیل', approved: 'تأییدشده', rejected: 'ردشده', archived: 'بایگانی‌شده' },
};
type Target = { workspace_id: string; workspace_type: string; environment: string };
type Opportunity = { opportunity_id: string; name: string; city: string; currency: string; asking_price: string; status: string };
type ManagementPortfolio = ReturnType<typeof managementPortfolioResponseV1Schema.parse>;
export function CustomerAirpropWorkspace({ lang }: { lang: Language }) {
 const { active } = useCustomerContext();
 return <section className="mx-auto max-w-5xl space-y-6 p-6" dir={lang === 'fa' ? 'rtl' : 'ltr'}>
  <h1 className="text-2xl font-semibold">{copy[lang].title}</h1>
  {active ? <WorkspaceSelection key={active.context_id} contextId={active.context_id} lang={lang} /> : <p>{copy[lang].context}</p>}
 </section>;
}
function WorkspaceSelection({ contextId, lang }: { contextId: string; lang: Language }) {
 const t=copy[lang]; const [targets,setTargets]=useState<Target[]|null>(null),[workspace,setWorkspace]=useState(''),[error,setError]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/customer/v1/workspace/targets?context_id=${encodeURIComponent(contextId)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();const body=await r.json();if(!Array.isArray(body.workspaces))throw new Error();if(controller.signal.aborted)return;setTargets(body.workspaces);}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[contextId]);
 if(error)return <p role="alert">{t.error}</p>;
 if(!targets)return <p role="status">{t.loading}</p>;
 if(!targets.length)return <p>{t.empty}</p>;
 return <div className="space-y-6"><label className="block">{t.choose}<select className="ms-3 rounded border p-2" value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">—</option>{targets.map(x=><option key={x.workspace_id} value={x.workspace_id}>{x.workspace_type} · {x.environment}</option>)}</select></label>
  {workspace&&<><ManagementPortfolioWizard key={`management:${workspace}`} contextId={contextId} workspaceId={workspace} lang={lang}/><OpportunityPanel key={workspace} contextId={contextId} workspaceId={workspace} lang={lang}/></>}</div>;
}

const managementCopy = {
 en: { title:'Managed portfolio', intro:'Review the current management scope before opening operational detail.', select:'1. Select property', mandate:'2. Review mandate', actions:'3. Review references', choose:'Choose a named property', empty:'No currently authorized managed property is available.', loading:'Loading managed portfolio…', error:'The managed portfolio is unavailable with the current access.', refresh:'Refresh access', next:'Continue', back:'Back', owner:'Owner', scope:'Commercial scope', duration:'Mandate period', actionTitle:'Operations references', noActions:'No Operations reference has been recorded.', operations:'Live Work Order detail remains in Operations. Statuses shown here are immutable link-time snapshots.', finance:'Finance detail is not connected until its canonical receipt contract is accepted.', listing:'Listing', lease_administration:'Lease administration', maintenance_coordination:'Maintenance coordination', owner_reporting:'Owner reporting', rent_collection:'Rent collection', supplier_coordination:'Supplier coordination', scheduled:'Scheduled', assigned:'Assigned', in_progress:'In progress', blocked:'Blocked', completed:'Completed', verified:'Verified' },
 ro: { title:'Portofoliu administrat', intro:'Verificați mandatul curent înainte de a deschide detaliile operaționale.', select:'1. Selectați proprietatea', mandate:'2. Verificați mandatul', actions:'3. Verificați referințele', choose:'Alegeți o proprietate după nume', empty:'Nu există proprietăți administrate autorizate în prezent.', loading:'Se încarcă portofoliul administrat…', error:'Portofoliul administrat nu este disponibil cu accesul curent.', refresh:'Reverifică accesul', next:'Continuă', back:'Înapoi', owner:'Proprietar', scope:'Domeniu comercial', duration:'Perioada mandatului', actionTitle:'Referințe Operațiuni', noActions:'Nu a fost înregistrată nicio referință Operațiuni.', operations:'Detaliul actual al ordinului de lucru rămâne în Operațiuni. Stările afișate sunt instantanee imuabile la momentul legării.', finance:'Detaliul Finance nu este conectat până la acceptarea contractului canonic de chitanță.', listing:'Listare', lease_administration:'Administrare închiriere', maintenance_coordination:'Coordonare mentenanță', owner_reporting:'Raportare proprietar', rent_collection:'Colectare chirie', supplier_coordination:'Coordonare furnizori', scheduled:'Programat', assigned:'Alocat', in_progress:'În lucru', blocked:'Blocat', completed:'Finalizat', verified:'Verificat' },
 fa: { title:'سبد مدیریت‌شده', intro:'پیش از مشاهدهٔ جزئیات عملیاتی، دامنهٔ مأموریت جاری را بررسی کنید.', select:'۱. انتخاب ملک', mandate:'۲. بررسی مأموریت', actions:'۳. بررسی ارجاع‌ها', choose:'ملک را با نام انتخاب کنید', empty:'در حال حاضر ملک مدیریت‌شدهٔ مجازی در دسترس نیست.', loading:'در حال دریافت سبد مدیریت‌شده…', error:'سبد مدیریت‌شده با دسترسی فعلی در دسترس نیست.', refresh:'بازبینی دسترسی', next:'ادامه', back:'بازگشت', owner:'مالک', scope:'دامنهٔ تجاری', duration:'دورهٔ مأموریت', actionTitle:'ارجاع‌های عملیات', noActions:'هنوز ارجاعی به عملیات ثبت نشده است.', operations:'جزئیات زندهٔ دستور کار در Operations باقی می‌ماند. وضعیت‌های این صفحه snapshot تغییرناپذیر زمان پیوند هستند.', finance:'تا پذیرش قرارداد canonical رسید، جزئیات Finance متصل نیست.', listing:'عرضه', lease_administration:'مدیریت اجاره', maintenance_coordination:'هماهنگی تعمیرات', owner_reporting:'گزارش مالک', rent_collection:'وصول اجاره', supplier_coordination:'هماهنگی تأمین‌کننده', scheduled:'زمان‌بندی‌شده', assigned:'تخصیص‌یافته', in_progress:'در حال اجرا', blocked:'متوقف', completed:'تکمیل‌شده', verified:'راستی‌آزمایی‌شده' },
} as const;

function ManagementPortfolioWizard({contextId,workspaceId,lang}:{contextId:string;workspaceId:string;lang:Language}) {
 const t=managementCopy[lang];
 const [report,setReport]=useState<ManagementPortfolio|null>(null),[failed,setFailed]=useState(false),[nonce,setNonce]=useState(0),[selectedId,setSelectedId]=useState(''),[step,setStep]=useState<1|2|3>(1);
 useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({context_id:contextId,workspace_id:workspaceId});
  fetch(`/api/customer/v2/airprop/commercial-lifecycle?${query}`,{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const parsed=managementPortfolioResponseV1Schema.parse(await response.json());if(controller.signal.aborted)return;setReport(parsed);setSelectedId(parsed.properties[0]?.mandate_request_id??'');setStep(1);setFailed(false);}).catch(()=>{if(!controller.signal.aborted){setReport(null);setSelectedId('');setFailed(true);}});return()=>controller.abort();
 },[contextId,workspaceId,nonce]);
 const selected=report?.properties.find(item=>item.mandate_request_id===selectedId);
 const locale=lang==='fa'?'fa-IR':lang==='ro'?'ro-RO':'en-GB';
 const date=(value:string)=>new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));
 const steps=[t.select,t.mandate,t.actions];
 return <section aria-label={t.title} className="rounded-2xl border border-amber-200 bg-amber-50/40 p-5" dir={lang==='fa'?'rtl':'ltr'}>
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">{t.title}</h2><p className="mt-1 text-sm text-slate-600">{t.intro}</p></div><button type="button" onClick={()=>setNonce(value=>value+1)} className="rounded-lg border border-slate-400 bg-white px-3 py-2 font-medium">{t.refresh}</button></div>
  <ol className="mt-4 grid gap-2 sm:grid-cols-3">{steps.map((label,index)=><li key={label} aria-current={step===index+1?'step':undefined} className={`rounded-lg border p-2 text-sm ${step===index+1?'border-amber-600 bg-white font-semibold':'border-slate-200 text-slate-500'}`}>{label}</li>)}</ol>
  {failed?<p role="alert" className="mt-4 text-red-800">{t.error}</p>:!report?<p role="status" className="mt-4">{t.loading}</p>:report.properties.length===0?<p className="mt-4">{t.empty}</p>:step===1?<div className="mt-4 space-y-3"><p className="font-medium">{t.choose}</p><div className="grid gap-2 sm:grid-cols-2">{report.properties.map(item=><button type="button" key={item.mandate_request_id} aria-pressed={selectedId===item.mandate_request_id} onClick={()=>setSelectedId(item.mandate_request_id)} className={`rounded-xl border bg-white p-3 text-start ${selectedId===item.mandate_request_id?'border-amber-600 ring-2 ring-amber-200':'border-slate-200'}`}><span className="block font-semibold">{item.property.label}</span><span className="block text-sm text-slate-600">{t.owner}: {item.owner.label}</span></button>)}</div><button type="button" disabled={!selected} onClick={()=>setStep(2)} className="rounded-lg bg-slate-900 px-4 py-2 text-white disabled:opacity-50">{t.next}</button></div>:selected&&step===2?<div className="mt-4 space-y-4 rounded-xl bg-white p-4"><h3 className="text-lg font-semibold">{selected.property.label}</h3><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">{t.owner}</dt><dd>{selected.owner.label}</dd></div><div><dt className="text-sm text-slate-500">{t.duration}</dt><dd>{date(selected.valid_from)} – {date(selected.valid_to)}</dd></div><div className="sm:col-span-2"><dt className="text-sm text-slate-500">{t.scope}</dt><dd className="mt-1 flex flex-wrap gap-2">{selected.scope.capabilities.map(capability=><span key={capability} className="rounded-full bg-amber-100 px-3 py-1 text-sm">{t[capability]}</span>)}</dd></div></dl><div className="flex gap-2"><button type="button" onClick={()=>setStep(1)} className="rounded-lg border px-4 py-2">{t.back}</button><button type="button" onClick={()=>setStep(3)} className="rounded-lg bg-slate-900 px-4 py-2 text-white">{t.next}</button></div></div>:selected?<div className="mt-4 space-y-4 rounded-xl bg-white p-4"><h3 className="text-lg font-semibold">{t.actionTitle}</h3>{selected.action_links.length===0?<p>{t.noActions}</p>:<ul className="space-y-2">{selected.action_links.map(action=><li key={action.action_link_id} className="rounded-lg border p-3"><span className="font-medium">{t[action.source_status_snapshot]}</span><span className="ms-2 text-sm text-slate-500">{new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(action.linked_at))}</span></li>)}</ul>}<p className="rounded-lg bg-sky-50 p-3 text-sm">{t.operations}</p><p className="rounded-lg bg-slate-100 p-3 text-sm">{t.finance}</p><button type="button" onClick={()=>setStep(2)} className="rounded-lg border px-4 py-2">{t.back}</button></div>:null}
 </section>;
}
function OpportunityPanel({ contextId,workspaceId,lang }: { contextId:string;workspaceId:string;lang:Language }) {
 const t=copy[lang]; const [rows,setRows]=useState<Opportunity[]|null>(null),[loadError,setLoadError]=useState(false),[nonce,setNonce]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[uncertain,setUncertain]=useState(false);
 const [name,setName]=useState(''),[city,setCity]=useState(''),[price,setPrice]=useState(''),[currency,setCurrency]=useState('EUR');
 const [selectedOpportunity,setSelectedOpportunity]=useState('');
 const formId=useId();
 const [fieldErrors,setFieldErrors]=useState<Record<string,boolean>>({});
 const formRef=useRef<HTMLFormElement>(null);
 const selected=rows?.find(row=>row.opportunity_id===selectedOpportunity);
 const evaluate=lang==='fa'?'ارزیابی':lang==='ro'?'Analizează':'Evaluate';
 const pending=useRef<ReturnType<typeof createAirpropOpportunityV2Schema.parse>|null>(null);
 const alive=useRef(true);
 const storageKey=`cladora.airprop.pending.v2:${contextId}:${workspaceId}`;
 const [recovering,setRecovering]=useState(true);
 useEffect(()=>{let cancelled=false;Promise.resolve().then(()=>{if(cancelled)return;try{const saved=sessionStorage.getItem(storageKey);if(saved){const parsed=createAirpropOpportunityV2Schema.safeParse(JSON.parse(saved));if(parsed.success&&parsed.data.context_id===contextId&&parsed.data.workspace_id===workspaceId){pending.current=parsed.data;const p=parsed.data.payload;setName(p.name);setCity(p.city);setPrice(p.asking_price);setCurrency(p.currency);setUncertain(true);setMessage(t.pending);}else sessionStorage.removeItem(storageKey);}}catch{setMessage(t.error);}setRecovering(false);});return()=>{cancelled=true;};},[storageKey,contextId,workspaceId,t.pending,t.error]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/customer/v2/airprop/opportunities?context_id=${encodeURIComponent(contextId)}&workspace_id=${encodeURIComponent(workspaceId)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();const body=await r.json();if(!Array.isArray(body.opportunities))throw new Error();if(controller.signal.aborted)return;setRows(body.opportunities);setLoadError(false);}).catch(()=>{if(!controller.signal.aborted)setLoadError(true);});return()=>controller.abort();},[contextId,workspaceId,nonce]);
 async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;
  if(!pending.current){const parsed=createAirpropOpportunityV2Schema.safeParse({version:2,context_id:contextId,workspace_id:workspaceId,idempotency_key:crypto.randomUUID(),payload:{name,city,asking_price:price,currency,country_code:'RO'}});if(!parsed.success){const errors=Object.fromEntries(parsed.error.issues.filter(issue=>issue.path[0]==='payload').map(issue=>[String(issue.path[1]),true]));setFieldErrors(errors);setMessage(t.invalid);const first=['name','city','asking_price','currency'].find(field=>errors[field]);if(first)(formRef.current?.elements.namedItem(first) as HTMLElement|null)?.focus();return;}setFieldErrors({});pending.current=parsed.data;}
  try{sessionStorage.setItem(storageKey,JSON.stringify(pending.current));}catch{setMessage(t.error);return;}
  setBusy(true);setMessage('');
  try{const r=await fetch('/api/customer/v2/airprop/opportunities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(pending.current)});
   if(!alive.current)return;
   if(r.ok){const body=await r.json();if(body.version!==2||body.workspace_id!==workspaceId||!body.opportunity_id)throw new Error();sessionStorage.removeItem(storageKey);pending.current=null;setUncertain(false);setName('');setCity('');setPrice('');setMessage(t.success);setNonce(n=>n+1);}
   else if(r.status>=500){setUncertain(true);setMessage(t.pending);}
   else {const body=await r.json();if(!uncertain){sessionStorage.removeItem(storageKey);pending.current=null;setUncertain(false);}setMessage(body.error?.code==='MFA_REQUIRED'?t.mfa:r.status===403?t.denied:t.invalid);}
  }catch{if(alive.current){setUncertain(true);setMessage(t.pending);}}finally{if(alive.current)setBusy(false);}
 }
 return <div className="space-y-6"><form ref={formRef} noValidate onSubmit={submit} className="space-y-3 rounded border p-4"><fieldset disabled={busy||uncertain||recovering} className="grid gap-3 sm:grid-cols-2">
  <label>{t.name}<input required name="name" aria-invalid={fieldErrors.name||undefined} aria-describedby={fieldErrors.name?`${formId}-name`:undefined} maxLength={160} className="block w-full rounded border p-2" value={name} onChange={e=>{setName(e.target.value);setFieldErrors(errors=>({...errors,name:false}));}}/>{fieldErrors.name&&<span id={`${formId}-name`} className="block text-sm text-red-700">{t.nameError}</span>}</label>
  <label>{t.city}<input required name="city" aria-invalid={fieldErrors.city||undefined} aria-describedby={fieldErrors.city?`${formId}-city`:undefined} maxLength={120} className="block w-full rounded border p-2" value={city} onChange={e=>{setCity(e.target.value);setFieldErrors(errors=>({...errors,city:false}));}}/>{fieldErrors.city&&<span id={`${formId}-city`} className="block text-sm text-red-700">{t.cityError}</span>}</label>
  <label>{t.price}<input required name="asking_price" aria-invalid={fieldErrors.asking_price||undefined} aria-describedby={fieldErrors.asking_price?`${formId}-asking_price`:undefined} inputMode="decimal" dir="ltr" className="block w-full rounded border p-2" value={price} onChange={e=>{setPrice(e.target.value);setFieldErrors(errors=>({...errors,asking_price:false}));}}/>{fieldErrors.asking_price&&<span id={`${formId}-asking_price`} className="block text-sm text-red-700">{t.priceError}</span>}</label>
  <label>{t.currency}<select className="block w-full rounded border p-2" value={currency} onChange={e=>setCurrency(e.target.value)}><option>EUR</option><option>RON</option></select></label>
 </fieldset><button disabled={busy||recovering} className="rounded bg-slate-900 px-4 py-2 text-white">{busy?t.loading:uncertain?t.retry:t.create}</button><p role="status" aria-live="polite">{message}</p></form>
 <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{t.opportunities}</h2><button type="button" className="rounded border border-slate-400 px-3 py-2 font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2" onClick={()=>setNonce(n=>n+1)}>{t.refresh}</button></div>
 {loadError?<p role="alert">{t.error}</p>:!rows?<p>{t.loading}</p>:!rows.length?<p>{t.none}</p>:<div className="overflow-x-auto"><table className="w-full text-start"><thead><tr>{[t.name,t.city,t.price,t.status,evaluate].map(x=><th key={x} className="p-2 text-start">{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.opportunity_id}><td className="p-2">{row.name}</td><td className="p-2">{row.city}</td><td className="p-2" dir="ltr">{row.asking_price} {row.currency}</td><td className="p-2">{t[row.status as keyof typeof t]??row.status}</td><td className="p-2"><button type="button" className="rounded border border-slate-400 px-3 py-2 font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2" aria-pressed={selectedOpportunity===row.opportunity_id} aria-label={`${evaluate}: ${row.name}`} onClick={()=>setSelectedOpportunity(row.opportunity_id)}>{evaluate}</button></td></tr>)}</tbody></table></div>}
 {selected&&!loadError&&<CustomerAirpropUnderwriting contextId={contextId} workspaceId={workspaceId} opportunityId={selected.opportunity_id} opportunityName={selected.name} currency={selected.currency} lang={lang} onSaved={()=>setNonce(n=>n+1)}/>}
 {selected&&!loadError&&<CustomerAirpropDiligence contextId={contextId} workspaceId={workspaceId} opportunityId={selected.opportunity_id} opportunityName={selected.name} lang={lang} refreshToken={nonce}/>}
 </div>;
}
