'use client';
import { useCallback, useEffect, useState } from 'react';
import { CalendarCheck, CheckCircle2, RefreshCw, ShieldCheck } from 'lucide-react';
import type { Language } from '@/types';
import { useCustomerContext } from './CustomerContextProvider';

type Period={id:string;starts_on:string;ends_on:string;status:'open'|'closed'};
type Cycle={id:string;property_id:string;accounting_period_id:string;status:string;currency:string;sources:number;approved_reviews:number;blocking_exceptions:number;snapshot_hash:string|null};
const words={
 ro:{title:'Ciclul financiar lunar',sub:'Colectare → alocare → revizuire independentă → publicare → închidere',newCycle:'Începe ciclul',source:'ID sursă / alocare',capture:'Atașează alocarea aprobată',submit:'Trimite la revizuire',approve:'Aprobă revizuirea',publish:'Publică instantaneul',close:'Închide perioada',refresh:'Actualizează',empty:'Nu există cicluri lunare.',guard:'Închiderea directă este dezactivată. Sunt obligatorii aprobările independente ale președintelui și cenzorului.',error:'Cererea a fost respinsă în siguranță de server.'},
 en:{title:'Monthly financial cycle',sub:'Collect → allocate → independent review → publish → close',newCycle:'Start cycle',source:'Source / allocation ID',capture:'Attach approved allocation',submit:'Submit for review',approve:'Approve review',publish:'Publish snapshot',close:'Close period',refresh:'Refresh',empty:'No monthly cycles yet.',guard:'Direct period close is disabled. Independent president and censor approvals are mandatory.',error:'The server safely rejected this request.'},
 fa:{title:'چرخه مالی ماهانه',sub:'جمع‌آوری ← تخصیص ← بازبینی مستقل ← انتشار ← بستن',newCycle:'آغاز چرخه',source:'شناسه منبع / تخصیص',capture:'اتصال تخصیص تأییدشده',submit:'ارسال برای بازبینی',approve:'تأیید بازبینی',publish:'انتشار اسنپ‌شات',close:'بستن دوره',refresh:'به‌روزرسانی',empty:'هنوز چرخه ماهانه‌ای وجود ندارد.',guard:'بستن مستقیم دوره غیرفعال است؛ تأیید مستقل رئیس و بازرس الزامی است.',error:'درخواست به‌صورت امن توسط سرور رد شد.'}
};
export function CustomerMonthlyCycleDashboard({lang}:{lang:Language}){
 const {active,dashboard}=useCustomerContext();const t=words[lang];const propertyId=dashboard?.context?.property_id??null;const role=dashboard?.context?.role_code;
 const [periods,setPeriods]=useState<Period[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[periodId,setPeriodId]=useState(''),[sourceId,setSourceId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{if(!active)return;setBusy(true);setError('');try{const [p,c]=await Promise.all([fetch(`/api/customer/v1/accounting/periods?context_id=${active.context_id}`,{cache:'no-store'}),fetch(`/api/customer/v1/accounting/monthly-cycles?context_id=${active.context_id}${propertyId?`&property_id=${propertyId}`:''}`,{cache:'no-store'})]);if(!p.ok||!c.ok)throw new Error();const pj=await p.json(),cj=await c.json();setPeriods(pj.periods??[]);setCycles(cj.cycles??[]);setPeriodId(v=>v||pj.periods?.find((x:Period)=>x.status==='open')?.id||'');}catch{setError(t.error)}finally{setBusy(false)}},[active,propertyId,t.error]);
 useEffect(()=>{const timer=setTimeout(()=>{void load()},0);return()=>clearTimeout(timer)},[load]);
 const canManage=role==='association_admin'||role==='property_manager';const canReview=role==='president'||role==='censor';
 async function mutate(path:string,body:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,context_id:active?.context_id})});if(!r.ok)throw new Error();await load()}catch{setError(t.error)}finally{setBusy(false)}}
 return <section className="space-y-6" dir={lang==='fa'?'rtl':'ltr'}>
  <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-[#102A43]">{t.title}</h1><p className="text-sm text-[#52667A]">{t.sub}</p></div><button onClick={()=>void load()} disabled={busy} className="flex gap-2 rounded-xl border bg-white px-4 py-2"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>{t.refresh}</button></header>
  <div className="flex items-center gap-3 rounded-2xl border border-teal-200 bg-teal-50 p-4 text-sm text-teal-900"><ShieldCheck className="h-5 w-5"/>{t.guard}</div>
  {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-800">{error}</div>}
  {canManage&&propertyId&&<div className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><select value={periodId} onChange={e=>setPeriodId(e.target.value)} className="rounded-xl border px-3 py-2">{periods.filter(p=>p.status==='open').map(p=><option key={p.id} value={p.id}>{p.starts_on} — {p.ends_on}</option>)}</select><button disabled={busy||!periodId} onClick={()=>void mutate('/api/customer/v1/accounting/monthly-cycles',{property_id:propertyId,period_id:periodId,currency:'RON'})} className="rounded-xl bg-[#0A6E62] px-4 py-2 font-semibold text-white">{t.newCycle}</button></div>}
  <div className="grid gap-4">{cycles.length===0?<p className="rounded-2xl border bg-white p-6 text-slate-500">{t.empty}</p>:cycles.map(c=><article key={c.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-bold text-[#102A43]">{c.status}</div><div className="text-xs text-slate-500">{c.accounting_period_id}</div></div><div className="flex gap-3 text-xs"><span>{c.sources} sources</span><span>{c.approved_reviews}/2 reviews</span><span>{c.blocking_exceptions} blockers</span></div></div>
   {canManage&&c.status==='collecting'&&<div className="mt-4 flex flex-wrap gap-2"><input value={sourceId} onChange={e=>setSourceId(e.target.value)} placeholder={t.source} className="min-w-72 rounded-xl border px-3 py-2"/><button disabled={busy||!sourceId} onClick={()=>void mutate(`/api/customer/v1/accounting/monthly-cycles/${c.id}/capture-source`,{source_type:'allocation_run',source_id:sourceId})} className="rounded-xl border px-3 py-2">{t.capture}</button><button disabled={busy||!sourceId} onClick={()=>void mutate(`/api/customer/v1/accounting/monthly-cycles/${c.id}/submit`,{allocation_run_id:sourceId})} className="rounded-xl bg-[#102A43] px-3 py-2 text-white">{t.submit}</button></div>}
   {canReview&&c.status==='pending_review'&&<button disabled={busy} onClick={()=>void mutate(`/api/customer/v1/accounting/monthly-cycles/${c.id}/review`,{decision:'approved'})} className="mt-4 rounded-xl bg-teal-700 px-3 py-2 text-white">{t.approve}</button>}
   {(role==='association_admin')&&c.status==='pending_review'&&c.approved_reviews===2&&<button disabled={busy} onClick={()=>void mutate(`/api/customer/v1/accounting/monthly-cycles/${c.id}/publish`,{})} className="mt-4 rounded-xl bg-teal-700 px-3 py-2 text-white">{t.publish}</button>}
   {(role==='association_admin')&&c.status==='close_ready'&&<button disabled={busy} onClick={()=>void mutate(`/api/customer/v1/accounting/monthly-cycles/${c.id}/close`,{reason:'Canonical monthly close'})} className="mt-4 flex items-center gap-2 rounded-xl bg-[#102A43] px-3 py-2 text-white"><CalendarCheck className="h-4 w-4"/>{t.close}</button>}
   {c.status==='closed'&&<CheckCircle2 className="mt-3 h-5 w-5 text-emerald-600"/>}
  </article>)}</div>
 </section>
}
