'use client';

import { useEffect, useId, useRef, useState } from 'react';
import { z } from 'zod';
import type { Language } from '@/types';
import { createAirpropUnderwritingV2Schema } from '@/lib/airprop/underwriting-contract-v2';

const copy = {
 en: { title:'Evaluation', history:'Version history', cost:'Acquisition cost', rent:'Annual rent', opex:'Annual operating expenses', currency:'Currency', save:'Save evaluation', retry:'Retry the same evaluation', refresh:'Refresh history', loading:'Loading…', empty:'No evaluations yet.', version:'Version', date:'Created', noi:'Annual net operating income', gross:'Gross yield', net:'Net yield', pending:'The result is uncertain. Retry this exact evaluation before starting another.', invalid:'Use positive acquisition cost and nonnegative rent and expenses, with a decimal point and up to four decimal places. Expenses must not exceed rent.', error:'Unable to load evaluation history.', storage:'The saved request could not be recovered or stored. Reload before continuing.', denied:'Your current access does not allow this action.', mfa:'Verify your identity to continue.', conflict:'This evaluation was rejected because the version, content or opportunity state changed. Refresh history before submitting a new evaluation.', success:'Evaluation saved.', hint:'Amounts use the opportunity currency.', costError:'Enter a positive acquisition cost, with up to 16 digits before the decimal point and four after it.', amountError:'Enter zero or a positive amount, with up to 16 digits before the decimal point and four after it.', relationError:'Operating expenses must not exceed annual rent. Review both amounts.' },
 ro: { title:'Analiză', history:'Istoricul versiunilor', cost:'Cost de achiziție', rent:'Chirie anuală', opex:'Cheltuieli anuale de exploatare', currency:'Monedă', save:'Salvează analiza', retry:'Reîncearcă aceeași analiză', refresh:'Actualizează istoricul', loading:'Se încarcă…', empty:'Nu există încă analize.', version:'Versiune', date:'Creată', noi:'Venit operațional net anual', gross:'Randament brut', net:'Randament net', pending:'Rezultatul este incert. Reîncearcă exact această analiză înainte de a începe alta.', invalid:'Introdu un cost de achiziție pozitiv și chirie și cheltuieli nenegative, cu punct zecimal și maximum patru zecimale. Cheltuielile nu pot depăși chiria.', error:'Istoricul analizelor nu poate fi încărcat.', storage:'Cererea salvată nu poate fi recuperată sau stocată. Reîncarcă pagina înainte de a continua.', denied:'Accesul actual nu permite această acțiune.', mfa:'Confirmă-ți identitatea pentru a continua.', conflict:'Analiza a fost respinsă deoarece versiunea, conținutul sau starea oportunității s-a schimbat. Actualizează istoricul înainte de o nouă analiză.', success:'Analiză salvată.', hint:'Sumele folosesc moneda oportunității.', costError:'Introdu un cost de achiziție pozitiv, cu maximum 16 cifre înainte de punctul zecimal și patru după acesta.', amountError:'Introdu zero sau o sumă pozitivă, cu maximum 16 cifre înainte de punctul zecimal și patru după acesta.', relationError:'Cheltuielile de exploatare nu pot depăși chiria anuală. Verifică ambele sume.' },
 fa: { title:'ارزیابی', history:'تاریخچهٔ نسخه‌ها', cost:'هزینهٔ خرید', rent:'اجارهٔ سالانه', opex:'هزینه‌های عملیاتی سالانه', currency:'ارز', save:'ثبت ارزیابی', retry:'ارسال مجدد همین ارزیابی', refresh:'تازه‌سازی تاریخچه', loading:'در حال دریافت…', empty:'هنوز ارزیابی ثبت نشده است.', version:'نسخه', date:'تاریخ ثبت', noi:'درآمد عملیاتی خالص سالانه', gross:'بازده ناخالص', net:'بازده خالص', pending:'نتیجه مشخص نیست. پیش از ارزیابی دیگر، همین درخواست را دوباره ارسال کنید.', invalid:'هزینهٔ خرید مثبت و اجاره و هزینه‌های نامنفی را با نقطهٔ اعشار و حداکثر چهار رقم اعشار وارد کنید. هزینه‌ها نباید بیشتر از اجاره باشند.', error:'تاریخچهٔ ارزیابی دریافت نشد.', storage:'بازیابی یا ذخیرهٔ درخواست ممکن نشد. پیش از ادامه صفحه را دوباره بارگذاری کنید.', denied:'این اقدام با دسترسی فعلی شما مجاز نیست.', mfa:'برای ادامه، هویت خود را تأیید کنید.', conflict:'ارزیابی به‌دلیل تغییر نسخه، محتوا یا وضعیت فرصت رد شد. پیش از ارزیابی جدید، تاریخچه را تازه‌سازی کنید.', success:'ارزیابی ثبت شد.', hint:'مبالغ با ارز فرصت ثبت می‌شوند.', costError:'هزینهٔ خرید مثبت را با حداکثر ۱۶ رقم پیش از نقطهٔ اعشار و ۴ رقم پس از آن وارد کنید.', amountError:'صفر یا مبلغ مثبت را با حداکثر ۱۶ رقم پیش از نقطهٔ اعشار و ۴ رقم پس از آن وارد کنید.', relationError:'هزینه‌های عملیاتی نباید بیشتر از اجارهٔ سالانه باشند. هر دو مبلغ را بررسی کنید.' },
};
const decimal = z.string().max(100).regex(/^\d+(?:\.\d+)?$/);
const signedDecimal = z.string().max(100).regex(/^-?\d+(?:\.\d+)?$/);
const results = z.object({annual_noi:signedDecimal,gross_yield:decimal,net_yield:signedDecimal,currency:z.string().regex(/^[A-Z]{3}$/)});
const historySchema = z.object({version:z.literal(2),workspace_id:z.string(),opportunity_id:z.string(),currency:z.enum(['EUR','RON']),underwriting_case_id:z.string().nullable(),current_version:z.number().int().nonnegative(),versions:z.array(z.object({evaluation_version:z.number().int().positive(),created_at:z.string(),assumptions:z.object({acquisition_cost:decimal,annual_rent:decimal,annual_opex:decimal,currency:z.string().regex(/^[a-zA-Z]{3}$/).nullable()}),results})).max(100)});
const savedSchema = z.object({version:z.literal(2),workspace_id:z.string(),opportunity_id:z.string(),underwriting_case_id:z.string(),evaluation_version:z.number().int().positive(),results,status:z.literal('underwriting'),idempotent:z.boolean()});
type Props = {contextId:string;workspaceId:string;opportunityId:string;opportunityName:string;currency:string;lang:Language;onSaved?:()=>void};
type Command = ReturnType<typeof createAirpropUnderwritingV2Schema.parse>;
// Moving the decimal point preserves the server's exact ratio without Number conversion.
function percent(ratio:string) { const sign=ratio.startsWith('-')?'-':'';const [whole,fraction='']=(sign?ratio.slice(1):ratio).split('.');const digits=fraction.padEnd(2,'0');return `${sign}${(whole+digits.slice(0,2)).replace(/^0+(?=\d)/,'')}${digits.length>2?`.${digits.slice(2)}`:''}%`; }

export function CustomerAirpropUnderwriting(props:Props) {
 // A changed authority or resource mounts a fresh state machine even if a caller forgets its key.
 return <Evaluation key={`${props.contextId}:${props.workspaceId}:${props.opportunityId}`} {...props}/>;
}
function Evaluation({contextId,workspaceId,opportunityId,opportunityName,currency,lang,onSaved}:Props) {
 const t=copy[lang];
 const formId=useId(),formRef=useRef<HTMLFormElement>(null);
 const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({});
 const [history,setHistory]=useState<z.infer<typeof historySchema>|null>(null),[loadError,setLoadError]=useState(false),[reload,setReload]=useState(0);
 const [cost,setCost]=useState(''),[rent,setRent]=useState(''),[opex,setOpex]=useState('');
 const [recovering,setRecovering]=useState(true),[blocked,setBlocked]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState<keyof typeof t|null>(null);
 const pending=useRef<Command|null>(null),inflight=useRef(false),generation=useRef(0);
 const storageKey=`cladora.airprop.underwriting.pending.v2:${contextId}:${workspaceId}:${opportunityId}`;
 useEffect(()=>{const epoch=++generation.current;Promise.resolve().then(()=>{if(generation.current!==epoch)return;try{const saved=sessionStorage.getItem(storageKey);if(saved){const p=createAirpropUnderwritingV2Schema.parse(JSON.parse(saved));if(p.context_id!==contextId||p.workspace_id!==workspaceId||p.opportunity_id!==opportunityId)throw new Error();pending.current=p;setCost(p.assumptions.acquisition_cost);setRent(p.assumptions.annual_rent);setOpex(p.assumptions.annual_opex);setUncertain(true);setMessage('pending');}}catch{setBlocked(true);setMessage('storage');}setRecovering(false);});return()=>{generation.current=epoch+1;};},[contextId,workspaceId,opportunityId,storageKey]);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/customer/v2/airprop/underwriting?context_id=${encodeURIComponent(contextId)}&workspace_id=${encodeURIComponent(workspaceId)}&opportunity_id=${encodeURIComponent(opportunityId)}&limit=100`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();const body=historySchema.parse(await r.json());if(body.workspace_id!==workspaceId||body.opportunity_id!==opportunityId||body.currency!==currency||body.versions.some(v=>(v.assumptions.currency!==null&&v.assumptions.currency.toUpperCase()!==v.results.currency)||v.evaluation_version>body.current_version))throw new Error();if(controller.signal.aborted)return;setHistory(body);setLoadError(false);}).catch(()=>{if(!controller.signal.aborted){setHistory(null);setLoadError(true);}});return()=>controller.abort();},[contextId,workspaceId,opportunityId,currency,reload]);
 function refresh(){setHistory(null);setLoadError(false);setReload(n=>n+1);}
 async function submit(event:React.FormEvent){event.preventDefault();if(inflight.current||recovering||blocked||(!pending.current&&(!history||loadError)))return;
  if(!pending.current){const p=createAirpropUnderwritingV2Schema.safeParse({version:2,context_id:contextId,workspace_id:workspaceId,opportunity_id:opportunityId,idempotency_key:crypto.randomUUID(),expected_version:history!.current_version,assumptions:{acquisition_cost:cost,annual_rent:rent,annual_opex:opex,currency:history!.currency}});if(!p.success){
   const errors:Record<string,string>={};
   for(const issue of p.error.issues){
    if(issue.path[0]!=='assumptions')continue;
    const field=issue.path[1];
    if(field==='acquisition_cost')errors[field]=t.costError;
    else if(field==='annual_rent'||field==='annual_opex')errors[field]=t.amountError;
    else if(issue.message==='opex_exceeds_rent')errors.annual_opex=t.relationError;
   }
   setFieldErrors(errors);setMessage('invalid');
   const first=['acquisition_cost','annual_rent','annual_opex'].find(field=>errors[field]);
   if(first)(formRef.current?.elements.namedItem(first) as HTMLElement|null)?.focus();
   return;
  }setFieldErrors({});pending.current=p.data;}
  const command=pending.current,epoch=generation.current;
  try{sessionStorage.setItem(storageKey,JSON.stringify(command));}catch{setBlocked(true);setMessage('storage');return;}
  inflight.current=true;setBusy(true);setMessage(null);
  try{const r=await fetch('/api/customer/v2/airprop/underwriting',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(command)});const body=await r.json();if(generation.current!==epoch)return;
   if(r.ok){const parsed=savedSchema.parse(body);if(parsed.workspace_id!==workspaceId||parsed.opportunity_id!==opportunityId||parsed.results.currency!==command.assumptions.currency||parsed.evaluation_version!==command.expected_version+1)throw new Error();sessionStorage.removeItem(storageKey);pending.current=null;setUncertain(false);setMessage('success');refresh();onSaved?.();}
   else if(r.status>=500){setUncertain(true);setMessage('pending');}
   else if(r.status===409&&['VERSION_CONFLICT','CONTENT_CONFLICT','STATE_CONFLICT','IDEMPOTENCY_CONFLICT'].includes(body.error?.code)){sessionStorage.removeItem(storageKey);pending.current=null;setUncertain(false);setMessage('conflict');setHistory(null);setLoadError(true);}
   else {setUncertain(true);setMessage(body.error?.code==='MFA_REQUIRED'?'mfa':r.status===401||r.status===403?'denied':'pending');}
  }catch{if(generation.current===epoch){setUncertain(true);setMessage('pending');}}finally{inflight.current=false;if(generation.current===epoch)setBusy(false);}
 }
 return <section className="space-y-4 rounded border p-4" dir={lang==='fa'?'rtl':'ltr'} aria-label={`${t.title}: ${opportunityName}`}>
  <h2 className="text-xl font-semibold">{t.title}: {opportunityName}</h2><p>{t.hint}</p>
  <form ref={formRef} noValidate onSubmit={submit} className="space-y-3"><fieldset disabled={busy||uncertain||recovering||blocked||!history} className="grid gap-3 sm:grid-cols-3">
   <label>{t.cost}<input required name="acquisition_cost" aria-invalid={Boolean(fieldErrors.acquisition_cost)||undefined} aria-describedby={fieldErrors.acquisition_cost?`${formId}-acquisition_cost`:undefined} inputMode="decimal" dir="ltr" className="block w-full rounded border p-2" value={cost} onChange={e=>{setCost(e.target.value);setFieldErrors({});}}/>{fieldErrors.acquisition_cost&&<span id={`${formId}-acquisition_cost`} className="block text-sm text-red-700">{fieldErrors.acquisition_cost}</span>}</label>
   <label>{t.rent}<input required name="annual_rent" aria-invalid={Boolean(fieldErrors.annual_rent)||undefined} aria-describedby={fieldErrors.annual_rent?`${formId}-annual_rent`:undefined} inputMode="decimal" dir="ltr" className="block w-full rounded border p-2" value={rent} onChange={e=>{setRent(e.target.value);setFieldErrors({});}}/>{fieldErrors.annual_rent&&<span id={`${formId}-annual_rent`} className="block text-sm text-red-700">{fieldErrors.annual_rent}</span>}</label>
   <label>{t.opex}<input required name="annual_opex" aria-invalid={Boolean(fieldErrors.annual_opex)||undefined} aria-describedby={fieldErrors.annual_opex?`${formId}-annual_opex`:undefined} inputMode="decimal" dir="ltr" className="block w-full rounded border p-2" value={opex} onChange={e=>{setOpex(e.target.value);setFieldErrors({});}}/>{fieldErrors.annual_opex&&<span id={`${formId}-annual_opex`} className="block text-sm text-red-700">{fieldErrors.annual_opex}</span>}</label>
  </fieldset><p>{t.currency}: <span dir="ltr">{history?.currency??currency}</span></p>
  <button disabled={busy||recovering||blocked||(!uncertain&&!history)} className="rounded bg-slate-900 px-4 py-2 text-white">{busy?t.loading:uncertain?t.retry:t.save}</button><p role="status" aria-live="polite">{message?t[message]:''}</p></form>
  <div className="flex items-center justify-between"><h3 className="font-semibold">{t.history}</h3><button type="button" disabled={busy} className="rounded border border-slate-400 px-3 py-2 font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2" onClick={refresh}>{t.refresh}</button></div>
  {loadError?<p role="alert">{t.error}</p>:!history?<p role="status">{t.loading}</p>:!history.versions.length?<p>{t.empty}</p>:<div className="overflow-x-auto"><table className="w-full"><thead><tr>{[t.version,t.date,t.cost,t.rent,t.opex,t.noi,t.gross,t.net].map(label=><th className="p-2 text-start" key={label}>{label}</th>)}</tr></thead><tbody>{history.versions.map(v=><tr key={v.evaluation_version}><td className="p-2">{v.evaluation_version}</td><td className="p-2" dir="ltr"><time dateTime={v.created_at}>{Number.isNaN(Date.parse(v.created_at))?'—':new Intl.DateTimeFormat(lang==='fa'?'fa-IR-u-ca-gregory':lang==='ro'?'ro-RO':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(v.created_at))} UTC</time></td>{[v.assumptions.acquisition_cost,v.assumptions.annual_rent,v.assumptions.annual_opex,v.results.annual_noi].map((amount,i)=><td className="p-2" dir="ltr" key={i}>{amount} {v.results.currency}</td>)}<td className="p-2" dir="ltr">{percent(v.results.gross_yield)}</td><td className="p-2" dir="ltr">{percent(v.results.net_yield)}</td></tr>)}</tbody></table></div>}
 </section>;
}
