'use client';
import {useCallback,useEffect,useState} from 'react';
import {AlertTriangle,ChevronLeft,ChevronRight,RefreshCw,Search,ShieldCheck,Wrench,X} from 'lucide-react';
import {PreventiveMaintenancePanel} from './PreventiveMaintenancePanel';
import {useCustomerContext} from './CustomerContextProvider';
type View='assets'|'components'|'plans'|'work_orders'|'tasks'|'vendors'|'sla'|'costs'|'history';
type Payload={total:number;rows:Record<string,unknown>[];summary:{assets:number;open_work_orders:number;overdue:number;cost_total:number};read_only:boolean};
const copy={en:{title:'Assets, Maintenance & Work Orders',sub:'Authorized lifecycle, maintenance, vendor, SLA and financial evidence calculated by the database.',assets:'Assets',components:'Components',plans:'Plans',work_orders:'Work orders',tasks:'Tasks',vendors:'Vendors',sla:'SLA',costs:'Costs',history:'Lifecycle',search:'Search authorized maintenance data',all:'All',status:'Status',priority:'Priority',from:'From',to:'To',refresh:'Refresh',loading:'Loading authorized maintenance evidence…',empty:'No maintenance records are visible in this context.',error:'Maintenance data could not be loaded.',readonly:'Read-only · server verified',details:'Details',close:'Close',open:'Open work orders',overdue:'Overdue',total:'Recorded cost',date:'Date / schedule',subject:'Asset / work order',source:'Location / vendor',value:'Value'},ro:{title:'Active, mentenanță și ordine de lucru',sub:'Ciclu de viață, furnizori, SLA și dovezi financiare autorizate, calculate în baza de date.',assets:'Active',components:'Componente',plans:'Planuri',work_orders:'Ordine de lucru',tasks:'Sarcini',vendors:'Furnizori',sla:'SLA',costs:'Costuri',history:'Istoric',search:'Caută date autorizate de mentenanță',all:'Toate',status:'Stare',priority:'Prioritate',from:'De la',to:'Până la',refresh:'Reîncarcă',loading:'Se încarcă dovezile autorizate…',empty:'Nu există înregistrări vizibile în acest context.',error:'Datele de mentenanță nu au putut fi încărcate.',readonly:'Doar citire · verificat de server',details:'Detalii',close:'Închide',open:'Ordine deschise',overdue:'Întârziate',total:'Cost înregistrat',date:'Dată / programare',subject:'Activ / ordin',source:'Locație / furnizor',value:'Valoare'},fa:{title:'دارایی‌ها، نگهداری و دستورکارها',sub:'چرخه عمر، فروشنده، SLA و شواهد مالی مجاز که در دیتابیس محاسبه می‌شوند.',assets:'دارایی‌ها',components:'اجزا',plans:'برنامه‌ها',work_orders:'دستورکارها',tasks:'وظایف',vendors:'فروشندگان',sla:'SLA',costs:'هزینه‌ها',history:'چرخه عمر',search:'جستجوی اطلاعات مجاز نگهداری',all:'همه',status:'وضعیت',priority:'اولویت',from:'از',to:'تا',refresh:'بازخوانی',loading:'در حال دریافت شواهد مجاز نگهداری…',empty:'در این زمینه رکوردی قابل مشاهده نیست.',error:'دریافت اطلاعات نگهداری ناموفق بود.',readonly:'فقط خواندنی · تأییدشده توسط سرور',details:'جزئیات',close:'بستن',open:'دستورکار باز',overdue:'عقب‌افتاده',total:'هزینه ثبت‌شده',date:'تاریخ / برنامه',subject:'دارایی / دستورکار',source:'محل / فروشنده',value:'مقدار'}} as const;
const txt=(v:unknown)=>v==null||v===''?'—':typeof v==='object'?JSON.stringify(v):String(v);const fmtDate=(v:unknown,l:string)=>v?new Intl.DateTimeFormat(l==='fa'?'fa-IR':l==='ro'?'ro-RO':'en-US').format(new Date(String(v))):'—';
export function CustomerMaintenanceDashboard({lang,initialView}:{lang:string;initialView:View}){const t=copy[lang==='fa'?'fa':lang==='ro'?'ro':'en'],{active}=useCustomerContext();const[view,setView]=useState<View>(initialView),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[offset,setOffset]=useState(0),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selected,setSelected]=useState<Record<string,unknown>|null>(null),[nonce,setNonce]=useState(0);
const load=useCallback(async()=>{if(!active){setLoading(false);setData(null);return}setLoading(true);setError('');try{const p=new URLSearchParams({context_id:active.context_id,view,limit:'20',offset:String(offset)});if(query)p.set('query',query);if(status)p.set('status',status);if(priority)p.set('priority',priority);if(from)p.set('from',from);if(to)p.set('to',to);const r=await fetch(`/api/customer/v1/maintenance?${p}`,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error();setData(await r.json())}catch{setError(t.error)}finally{setLoading(false)}},[active,view,offset,query,status,priority,from,to,t.error]);useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>clearTimeout(timer)},[load,nonce]);
const tabs=(['assets','components','plans','work_orders','tasks','vendors','sla','costs','history'] as View[]);function change(v:View){setView(v);setOffset(0);setStatus('');setSelected(null)}
return <div className="space-y-5"><header className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#0E9F8E]"><Wrench className="h-4 w-4"/>C09 · Maintenance evidence</div><h1 className="mt-1 text-2xl font-extrabold text-[#102A43]">{t.title}</h1><p className="mt-1 text-sm text-[#52667A]">{t.sub}</p></div><div className="h-fit rounded-xl border border-[#B2E5DF] bg-[#EAF8F5] px-3 py-2 text-xs font-bold text-[#0A6E62]"><ShieldCheck className="me-2 inline h-4 w-4"/>{t.readonly}</div></div></header>
<div className="flex flex-wrap gap-2">{tabs.map(v=><button type="button" key={v} onClick={()=>change(v)} className={`rounded-xl px-3 py-2 text-xs font-bold ${view===v?'bg-[#0E9F8E] text-white':'border bg-white text-[#334E68]'}`}>{t[v]}</button>)}</div>
{view==='plans'&&active?<PreventiveMaintenancePanel lang={lang==='fa'?'fa':lang==='ro'?'ro':'en'} contextId={active.context_id}/>:null}
<form onSubmit={e=>{e.preventDefault();setOffset(0);setQuery(draft.trim())}} className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-6"><label className="relative md:col-span-2"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]"/><span className="sr-only">{t.search}</span><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={t.search} className="w-full rounded-xl border py-2 pe-3 ps-9 text-sm"/></label><input aria-label={t.status} value={status} onChange={e=>{setStatus(e.target.value);setOffset(0)}} placeholder={`${t.all} · ${t.status}`} className="rounded-xl border px-3 py-2 text-sm"/><select aria-label={t.priority} value={priority} onChange={e=>{setPriority(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"><option value="">{t.all} · {t.priority}</option>{['low','normal','high','urgent','emergency'].map(x=><option key={x}>{x}</option>)}</select><input type="date" aria-label={t.from} value={from} onChange={e=>{setFrom(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"/><div className="flex gap-2"><input type="date" aria-label={t.to} value={to} onChange={e=>{setTo(e.target.value);setOffset(0)}} className="min-w-0 flex-1 rounded-xl border px-3 py-2 text-sm"/><button type="button" aria-label={t.refresh} onClick={()=>setNonce(n=>n+1)} className="rounded-xl border p-2"><RefreshCw className="h-4 w-4"/></button></div></form>
{data?.summary?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label={t.assets} value={data.summary.assets}/><Metric label={t.open} value={data.summary.open_work_orders}/><Metric label={t.overdue} value={data.summary.overdue} alert/><Metric label={t.total} value={data.summary.cost_total}/></div>:null}
{loading?<Box value={t.loading}/>:error?<Box value={error}/>:!data?.rows.length?<Box value={t.empty}/>:<><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-start text-xs"><thead className="bg-[#F6F9FC] text-[#52667A]"><tr><th className="p-3 text-start">{t.date}</th><th className="p-3 text-start">{t.subject}</th><th className="p-3 text-start">{t.source}</th><th className="p-3 text-start">{t.value}</th><th className="p-3 text-start">{t.status}</th><th className="p-3 text-start">{t.details}</th></tr></thead><tbody className="divide-y">{data.rows.map(r=><tr key={String(r.id)}><Cells row={r} view={view} lang={lang}/><td className="p-3"><button type="button" onClick={()=>setSelected(r)} className="font-bold text-[#087A6E]">{t.details}</button></td></tr>)}</tbody></table></div><div className="flex justify-between text-xs text-[#52667A]"><span>{offset+1}–{Math.min(offset+20,data.total)} / {data.total}</span><div className="flex gap-2"><button type="button" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-20))} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4 rtl:rotate-180"/></button><button type="button" disabled={offset+20>=data.total} onClick={()=>setOffset(offset+20)} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4 rtl:rotate-180"/></button></div></div></>}{selected?<Detail row={selected} close={()=>setSelected(null)} label={t.close}/>:null}</div>}
function Metric({label,value,alert}:{label:string;value:unknown;alert?:boolean}){return <div className="rounded-2xl border bg-white p-4"><div className="text-xs font-bold text-[#52667A]">{alert?<AlertTriangle className="me-1 inline h-4 w-4 text-[#E5484D]"/>:null}{label}</div><div className="mt-2 text-xl font-extrabold text-[#102A43]">{txt(value)}</div></div>}
function Box({value}:{value:string}){return <div className="rounded-2xl border bg-white p-10 text-center text-sm text-[#52667A]">{value}</div>}
function Cells({row:r,view,lang}:{row:Record<string,unknown>;view:View;lang:string}){const when=r.occurred_at??r.incurred_on??r.measured_at??r.created_at??r.next_due_at??r.installed_on??r.assigned_at;const subject=r.asset_name??r.work_order_title??r.name??r.component_name??r.vendor_name??r.event_type;const source=r.unit_code??r.building_name??r.property_name??r.vendor_name??r.parent_name??r.asset_code;const value=view==='costs'?`${txt(r.amount)} ${txt(r.currency)}`:view==='sla'?`${txt(r.actual_value)} / ${txt(r.target_value)} ${txt(r.unit_code)}`:view==='vendors'?r.rating:view==='components'?r.quantity:r.cost_totals??r.condition??r.default_priority??r.priority;return <><td className="p-3">{fmtDate(when,lang)}</td><td className="p-3 font-bold">{txt(subject)}</td><td className="p-3">{txt(source)}</td><td className="p-3 font-mono">{txt(value)}</td><td className="p-3">{txt(r.status??r.work_order_status??r.met??r.overdue)}</td></>}
function Detail({row,close,label}:{row:Record<string,unknown>;close:()=>void;label:string}){return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[80] grid place-items-center bg-black/60 p-4"><div className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-end"><button type="button" onClick={close} aria-label={label}><X/></button></div><dl className="grid gap-3 sm:grid-cols-2">{Object.entries(row).filter(([k])=>!['serial_number_encrypted','object_path','contract_ref_encrypted','tax_ref_encrypted','email_encrypted','phone_encrypted','snapshot_json','before_snapshot','after_snapshot'].includes(k)).map(([k,v])=><div key={k} className="rounded-xl bg-[#F6F9FC] p-3"><dt className="text-xs font-bold text-[#52667A]">{k}</dt><dd className="mt-1 break-words text-xs text-[#102A43]">{txt(v)}</dd></div>)}</dl></div></div>}
