'use client';
import { CustomerAirpropAcquisition } from './CustomerAirpropAcquisition';
import { useEffect, useRef, useState } from 'react';
import { z } from 'zod';
import type { Language } from '@/types';
import { useCustomerContext } from './CustomerContextProvider';
import { diligenceContentV1Schema, diligenceReviewCommandV1Schema } from '@/lib/airprop/diligence-review-command-v1';
import { createAirpropDiligenceDraftV1Schema } from '@/lib/airprop/diligence-draft-contract-v1';
const copy = {
 en:{staleEvidence:'Historical evidence; select a current verified version',title:'Due diligence',create:'Start due diligence',choose:'Select review baseline',documentContext:'Document access context',select:'Select…',empty:'Save an evaluation before starting due diligence.',loading:'Loading…',error:'Unable to load this review with current access. Check the document context and refresh.',refresh:'Refresh review',save:'Save review revision',submit:'Submit for review',submitted:'Submitted for review',draft:'Draft',legal:'Legal',financial:'Financial',technical:'Technical',pending:'Pending',satisfied:'Satisfied',evidence:'Verified evidence',none:'No authorized, verified and scanned documents are available in this context.',findings:'Findings',add:'Add finding',summary:'Summary',severity:'Severity',blocking:'Blocking',advisory:'Advisory',open:'Open',resolved:'Resolved',resolution:'Resolution',status:'Status',revision:'Revision',baseline:'Evaluation version',stale:'A newer evaluation exists. Start a new review against that version.',hint:'All three checks need verified evidence. Resolve blocking findings before submitting. Submission records the review; acquisition approval is a separate step.',uncertain:'The result is uncertain. Retry the same request before making another change.',retry:'Retry the same request',success:'Saved.',invalid:'Check findings, resolutions and evidence selections.',denied:'Current access does not permit this action.',mfa:'Verify your identity to continue.',conflict:'The version or review state changed. Refresh before making a new request.',storage:'The pending request cannot be recovered or stored. Reload before continuing.',readonly:'This review is read-only with current access.',notReady:'Save a complete checklist and resolve blocking findings before submitting.',chooseContext:'Select a document access context to view eligible evidence.',documentsLink:'Upload documents',uploadHint:'Upload property documents in Documents. They appear here after scanning and independent verification.',unsavedWarning:'Unsaved review edits will be lost. Save them first or discard them to continue.',keepEditing:'Keep editing',discardEdits:'Discard edits'},
 ro:{staleEvidence:'Dovadă istorică; selectează o versiune verificată curentă',title:'Verificare prealabilă',create:'Începe verificarea',choose:'Selectează baza verificării',documentContext:'Context de acces la documente',select:'Selectează…',empty:'Salvează o analiză înainte de verificare.',loading:'Se încarcă…',error:'Verificarea nu poate fi încărcată cu accesul actual. Verifică contextul documentelor și actualizează.',refresh:'Actualizează verificarea',save:'Salvează revizia',submit:'Trimite spre examinare',submitted:'Trimisă spre examinare',draft:'Ciornă',legal:'Juridic',financial:'Financiar',technical:'Tehnic',pending:'În așteptare',satisfied:'Îndeplinit',evidence:'Dovezi verificate',none:'Nu există documente autorizate, verificate și scanate în acest context.',findings:'Constatări',add:'Adaugă constatare',summary:'Rezumat',severity:'Severitate',blocking:'Blocantă',advisory:'Informativă',open:'Deschisă',resolved:'Rezolvată',resolution:'Rezolvare',status:'Stare',revision:'Revizie',baseline:'Versiunea analizei',stale:'Există o analiză mai nouă. Începe o verificare pe versiunea nouă.',hint:'Toate cele trei verificări necesită dovezi verificate. Rezolvă constatările blocante înainte de trimitere. Aprobarea achiziției este un pas separat.',uncertain:'Rezultatul este incert. Reîncearcă aceeași cerere înainte de alte modificări.',retry:'Reîncearcă aceeași cerere',success:'Salvat.',invalid:'Verifică constatările, rezolvările și dovezile selectate.',denied:'Accesul actual nu permite această acțiune.',mfa:'Confirmă-ți identitatea pentru a continua.',conflict:'Versiunea sau starea s-a schimbat. Actualizează înainte de o cerere nouă.',storage:'Cererea în așteptare nu poate fi recuperată sau stocată. Reîncarcă pagina.',readonly:'Verificarea poate fi doar consultată cu accesul actual.',notReady:'Salvează lista completă și rezolvă constatările blocante înainte de trimitere.',chooseContext:'Selectează contextul documentelor pentru a vedea dovezile eligibile.',documentsLink:'Încarcă documente',uploadHint:'Încarcă documentele proprietății în Documente. Vor apărea aici după scanare și verificare independentă.',unsavedWarning:'Modificările nesalvate se vor pierde. Salvează-le sau renunță la ele pentru a continua.',keepEditing:'Continuă editarea',discardEdits:'Renunță la modificări'},
 fa:{staleEvidence:'مدرک قبلی؛ نسخهٔ تأییدشدهٔ جاری را انتخاب کنید',title:'بررسی موشکافانه',create:'شروع بررسی موشکافانه',choose:'انتخاب مبنای بررسی',documentContext:'زمینهٔ دسترسی به مدارک',select:'انتخاب کنید…',empty:'ابتدا یک ارزیابی ثبت کنید.',loading:'در حال دریافت…',error:'بررسی با دسترسی فعلی دریافت نشد. زمینهٔ مدارک را بررسی و تازه‌سازی کنید.',refresh:'تازه‌سازی بررسی',save:'ثبت نسخهٔ بررسی',submit:'ارسال برای بازبینی',submitted:'ارسال‌شده برای بازبینی',draft:'پیش‌نویس',legal:'حقوقی',financial:'مالی',technical:'فنی',pending:'در انتظار بررسی',satisfied:'تکمیل‌شده',evidence:'مدارک تأییدشده',none:'در این زمینه، سند مجاز، تأییدشده و اسکن‌شده‌ای موجود نیست.',findings:'یافته‌ها',add:'افزودن یافته',summary:'شرح یافته',severity:'اهمیت',blocking:'مسدودکننده',advisory:'اطلاع‌رسانی',open:'باز',resolved:'رفع‌شده',resolution:'شرح رفع',status:'وضعیت',revision:'نسخهٔ بررسی',baseline:'نسخهٔ ارزیابی',stale:'ارزیابی جدیدتری موجود است. بررسی جدید را بر مبنای آن شروع کنید.',hint:'هر سه بررسی نیازمند مدرک تأییدشده هستند. یافته‌های مسدودکننده باید پیش از ارسال رفع شوند. ارسال برای بازبینی ثبت می‌شود؛ تأیید خرید مرحله‌ای جداگانه است.',uncertain:'نتیجه مشخص نیست. پیش از تغییر دیگر، همین درخواست را دوباره ارسال کنید.',retry:'ارسال مجدد همین درخواست',success:'ثبت شد.',invalid:'یافته‌ها، شرح رفع و مدارک انتخاب‌شده را بررسی کنید.',denied:'این اقدام با دسترسی فعلی مجاز نیست.',mfa:'برای ادامه، هویت خود را تأیید کنید.',conflict:'نسخه یا وضعیت بررسی تغییر کرده است. پیش از درخواست جدید تازه‌سازی کنید.',storage:'بازیابی یا ذخیرهٔ درخواست ممکن نشد. صفحه را دوباره بارگذاری کنید.',readonly:'با دسترسی فعلی، این بررسی فقط قابل مشاهده است.',notReady:'چک‌لیست کامل و رفع یافته‌های مسدودکننده را ثبت کنید، سپس ارسال کنید.',chooseContext:'برای دیدن مدارک مجاز، زمینهٔ دسترسی به مدارک را انتخاب کنید.',documentsLink:'بارگذاری مدارک',uploadHint:'مدارک ملک را در بخش اسناد بارگذاری کنید. پس از اسکن و تأیید مستقل، اینجا نمایش داده می‌شوند.',unsavedWarning:'تغییرات ذخیره‌نشده از بین می‌روند. ابتدا آن‌ها را ثبت کنید یا برای ادامه کنار بگذارید.',keepEditing:'ادامهٔ ویرایش',discardEdits:'کنارگذاشتن تغییرات'},
};
const uuid=z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
const reviewSchema=diligenceContentV1Schema.and(z.object({version:z.literal(1),workspace_id:uuid,opportunity_id:uuid,diligence_case_id:uuid,revision:z.number().int().positive(),underwriting_version:z.number().int().positive(),current_underwriting_version:z.number().int().positive(),policy_version:z.literal(1),status:z.enum(['draft','submitted']),can_manage:z.boolean(),can_submit:z.boolean(),ready_for_review:z.boolean()}));
const evidenceSchema=z.object({version:z.literal(1),workspace_id:uuid,opportunity_id:uuid,evidence:z.array(z.object({document_id:uuid,version_id:uuid,document_version:z.number().int().positive(),title:z.string()})).max(100)});
type Content=z.infer<typeof diligenceContentV1Schema>;
type Command=z.infer<typeof diligenceReviewCommandV1Schema>|z.infer<typeof createAirpropDiligenceDraftV1Schema>;
type Props={contextId:string;workspaceId:string;opportunityId:string;opportunityName:string;lang:Language;refreshToken?:number};
export function CustomerAirpropDiligence(props:Props){return <Diligence key={`${props.contextId}:${props.workspaceId}:${props.opportunityId}`} {...props}/>;}
function Diligence({contextId,workspaceId,opportunityId,opportunityName,lang,refreshToken}:Props){
 const t=copy[lang],{contexts}=useCustomerContext();const [reload,setReload]=useState(0),[cases,setCases]=useState<{diligence_case_id:string;underwriting_version:number}[]|null>(null),[baseline,setBaseline]=useState(0),[selected,setSelected]=useState(''),[docContext,setDocContext]=useState(''),[failed,setFailed]=useState(false),[unsaved,setUnsaved]=useState(false),[pendingChange,setPendingChange]=useState<{kind:'refresh'|'context'|'case';value?:string}|null>(null);
 const native={context_id:contextId,workspace_id:workspaceId,opportunity_id:opportunityId};
 const query=new URLSearchParams(native).toString();
 useEffect(()=>{const c=new AbortController();Promise.all([fetch(`/api/customer/v2/airprop/diligence?${query}`,{cache:'no-store',signal:c.signal}),fetch(`/api/customer/v2/airprop/underwriting?${query}&limit=1`,{cache:'no-store',signal:c.signal})]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error();const drafts=z.object({version:z.literal(1),workspace_id:uuid,opportunity_id:uuid,drafts:z.array(z.object({diligence_case_id:uuid,underwriting_version:z.number().int().positive()})).max(50)}).parse(await a.json());const history=z.object({workspace_id:uuid,opportunity_id:uuid,current_version:z.number().int().nonnegative()}).parse(await b.json());if([drafts,history].some(x=>x.workspace_id!==workspaceId||x.opportunity_id!==opportunityId))throw new Error();if(!c.signal.aborted){setCases(drafts.drafts);setBaseline(history.current_version);setFailed(false);}}).catch(()=>{if(!c.signal.aborted){setCases(null);setFailed(true);}});return()=>c.abort();},[query,workspaceId,opportunityId,reload,refreshToken]);
 function applyChange(change:{kind:'refresh'|'context'|'case';value?:string}){setPendingChange(null);if(change.kind==='refresh'){setCases(null);setReload(n=>n+1);}else if(change.kind==='context')setDocContext(change.value??'');else setSelected(change.value??'');}
 function requestChange(change:{kind:'refresh'|'context'|'case';value?:string}){if(unsaved)setPendingChange(change);else applyChange(change);}
 const physical=(contexts??[]).filter(x=>['property','building','unit'].includes(x.scope_type));
 return <section className="space-y-4 rounded border p-4" dir={lang==='fa'?'rtl':'ltr'} aria-label={`${t.title}: ${opportunityName}`}><h2 className="text-xl font-semibold">{t.title}: {opportunityName}</h2><p>{t.hint}</p>
 <button type="button" className="rounded border px-3 py-2" onClick={()=>requestChange({kind:'refresh'})}>{t.refresh}</button>
 {failed?<p role="alert">{t.error}</p>:!cases?<p role="status">{t.loading}</p>:<>
 {pendingChange&&<div role="alert" className="space-x-2 rounded border border-amber-600 p-3"><p>{t.unsavedWarning}</p><button type="button" className="rounded border px-3 py-2" onClick={()=>setPendingChange(null)}>{t.keepEditing}</button><button type="button" className="rounded border px-3 py-2" onClick={()=>{setUnsaved(false);applyChange(pendingChange);}}>{t.discardEdits}</button></div>}
 <label className="block">{t.documentContext}<select className="ms-3 rounded border p-2" value={docContext} onChange={e=>requestChange({kind:'context',value:e.target.value})}><option value="">{t.select}</option>{physical.map(x=><option key={x.context_id} value={x.context_id}>{x.tenant_name} · {x.context_label} · {x.role_name}</option>)}</select></label>
 <label className="block">{t.choose}<select className="ms-3 rounded border p-2" value={selected} onChange={e=>requestChange({kind:'case',value:e.target.value})}><option value="">{t.select}</option>{cases.map(x=><option key={x.diligence_case_id} value={x.diligence_case_id}>{t.baseline} {x.underwriting_version}</option>)}</select></label>
 {!baseline?<p>{t.empty}</p>:!cases.some(x=>x.underwriting_version===baseline)&&<DraftStart key={baseline} native={native} baseline={baseline} lang={lang} onSaved={id=>{setSelected(id);setReload(n=>n+1);}}/>}
 {selected&&cases.some(x=>x.diligence_case_id===selected)&&<ReviewEditor key={`${selected}:${docContext}`} native={native} caseId={selected} docContext={docContext} lang={lang} reloadParent={reload} onDirtyChange={setUnsaved}/>}
 </>}
 </section>;
}
type Native={context_id:string;workspace_id:string;opportunity_id:string};
function useCommand(native:Native,scope:string,lang:Language,onSaved:(body:Record<string,unknown>)=>void){
 const t=copy[lang],[busy,setBusy]=useState(false),[recovering,setRecovering]=useState(true),[blocked,setBlocked]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState<keyof typeof t|null>(null);
 const pending=useRef<Command|null>(null),inflight=useRef(false),epoch=useRef(0),storageKey=`cladora.airprop.diligence.pending.v1:${native.context_id}:${native.workspace_id}:${native.opportunity_id}:${scope}`;
 useEffect(()=>{const generation=++epoch.current;Promise.resolve().then(()=>{if(epoch.current!==generation)return;try{const saved=sessionStorage.getItem(storageKey);if(saved){const value=JSON.parse(saved);const p='action'in value?diligenceReviewCommandV1Schema.parse(value):createAirpropDiligenceDraftV1Schema.parse(value);if(p.context_id!==native.context_id||p.workspace_id!==native.workspace_id||p.opportunity_id!==native.opportunity_id||('action'in p?`${p.diligence_case_id}:${p.document_context_id}`:`create:${p.expected_underwriting_version}`)!==scope)throw new Error();pending.current=p;setUncertain(true);setMessage('uncertain');}}catch{setBlocked(true);setMessage('storage');}setRecovering(false);});return()=>{epoch.current=generation+1;};},[storageKey,native.context_id,native.workspace_id,native.opportunity_id,scope]);
 async function send(input:Command){if(inflight.current||recovering||blocked)return;const command=pending.current??input;pending.current=command;
 try{sessionStorage.setItem(storageKey,JSON.stringify(command));}catch{setBlocked(true);setMessage('storage');return;}
 inflight.current=true;setBusy(true);setMessage(null);const generation=epoch.current;
 try{const r=await fetch(`/api/customer/v2/airprop/diligence${'action'in command?'/review':''}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(command)});const body=await r.json();if(epoch.current!==generation)return;
 if(r.ok){const expected='action'in command?(command.action==='save'?command.expected_revision+1:command.expected_revision):1;
 if(body.version!==1||body.workspace_id!==native.workspace_id||body.opportunity_id!==native.opportunity_id||!uuid.safeParse(body.diligence_case_id).success||body.revision!==expected||typeof body.idempotent!=='boolean'||('action'in command&&(body.diligence_case_id!==command.diligence_case_id||body.status!==(command.action==='submit'?'submitted':'draft')))||(!('action'in command)&&(body.underwriting_version!==command.expected_underwriting_version||body.status!=='draft')))throw new Error();
 sessionStorage.removeItem(storageKey);pending.current=null;setUncertain(false);setMessage('success');onSaved(body);
 }else if(r.status===409){sessionStorage.removeItem(storageKey);pending.current=null;setUncertain(false);setMessage('conflict');onSaved({conflict:true});}
 else{setUncertain(true);setMessage(body.error?.code==='MFA_REQUIRED'?'mfa':r.status===401||r.status===403?'denied':r.status===400?'invalid':'uncertain');}
 }catch{if(epoch.current===generation){setUncertain(true);setMessage('uncertain');}}finally{inflight.current=false;if(epoch.current===generation)setBusy(false);}
 }
 return{busy,recovering,blocked,uncertain,message,setMessage,pending,send};
}
function DraftStart({native,baseline,lang,onSaved}:{native:Native;baseline:number;lang:Language;onSaved:(id:string)=>void}){
 const t=copy[lang],c=useCommand(native,`create:${baseline}`,lang,b=>{if(!b.conflict)onSaved(String(b.diligence_case_id));});
 return <div><button type="button" disabled={c.busy||c.recovering||c.blocked} className="rounded bg-slate-900 px-4 py-2 text-white" onClick={()=>void c.send({version:1,...native,expected_underwriting_version:baseline,idempotency_key:crypto.randomUUID()})}>{c.uncertain?t.retry:t.create}</button><p role="status">{c.message?t[c.message]:''}</p></div>;
}
function ReviewEditor({native,caseId,docContext,lang,reloadParent,onDirtyChange}:{native:Native;caseId:string;docContext:string;lang:Language;reloadParent:number;onDirtyChange:(dirty:boolean)=>void}){
 const t=copy[lang],[review,setReview]=useState<z.infer<typeof reviewSchema>|null>(null),[content,setContent]=useState<Content|null>(null),[evidence,setEvidence]=useState<z.infer<typeof evidenceSchema>['evidence']>([]),[failed,setFailed]=useState(false),[nonce,setNonce]=useState(0),[dirty,setDirty]=useState(false),[confirmRefresh,setConfirmRefresh]=useState(false);
 useEffect(()=>{onDirtyChange(dirty);},[dirty,onDirtyChange]);
 const command=useCommand(native,`${caseId}:${docContext}`,lang,()=>{setReview(null);setContent(null);setDirty(false);setNonce(n=>n+1);});
 const query=new URLSearchParams({...native,diligence_case_id:caseId,...(docContext?{document_context_id:docContext}:{})}).toString();
 const evidenceQuery=new URLSearchParams({...native,document_context_id:docContext}).toString();
 useEffect(()=>{const c=new AbortController();Promise.all([fetch(`/api/customer/v2/airprop/diligence/review?${query}`,{cache:'no-store',signal:c.signal}),docContext?fetch(`/api/customer/v2/airprop/diligence/evidence?${evidenceQuery}`,{cache:'no-store',signal:c.signal}):Promise.resolve(null)]).then(async([r,e])=>{if(!r.ok||(e&&!e.ok))throw new Error();const body=reviewSchema.parse(await r.json());if(body.workspace_id!==native.workspace_id||body.opportunity_id!==native.opportunity_id||body.diligence_case_id!==caseId)throw new Error();let files:z.infer<typeof evidenceSchema>['evidence']=[];if(e){const b=evidenceSchema.parse(await e.json());if(b.workspace_id!==native.workspace_id||b.opportunity_id!==native.opportunity_id)throw new Error();files=b.evidence;}if(!c.signal.aborted){setReview(body);setContent({checklist:body.checklist,findings:body.findings});setEvidence(files);setDirty(false);setFailed(false);}}).catch(()=>{if(!c.signal.aborted){setReview(null);setContent(null);setEvidence([]);setFailed(true);}});return()=>c.abort();},[query,evidenceQuery,docContext,caseId,native.workspace_id,native.opportunity_id,nonce,reloadParent]);
 function mutate(value:Content){setContent(value);setDirty(true);}
 const disabled=command.busy||command.uncertain||command.recovering||command.blocked||!review||!docContext||!review.can_manage||review.status==='submitted'||review.underwriting_version!==review.current_underwriting_version;
 function send(action:'save'|'submit'){if(!review||!content)return;const parsed=diligenceReviewCommandV1Schema.safeParse({version:1,...native,action,diligence_case_id:caseId,document_context_id:docContext,expected_revision:review.revision,idempotency_key:crypto.randomUUID(),...(action==='save'?{snapshot:content}:{expected_underwriting_version:review.underwriting_version,expected_policy_version:1})});if(!parsed.success){command.setMessage('invalid');return;}void command.send(parsed.data);}
 function versions(ids:string[],onChange:(ids:string[])=>void,label:string){return <label className="block">{label}<select multiple size={Math.min(5,Math.max(2,evidence.length))} className="block w-full rounded border p-2" value={ids} onChange={e=>onChange(Array.from(e.target.selectedOptions,x=>x.value))}>{ids.filter(id=>!evidence.some(e=>e.version_id===id)).map(id=><option key={id} value={id}>{t.staleEvidence}</option>)}{evidence.map(e=><option key={e.version_id} value={e.version_id}>{e.title} · {t.revision} {e.document_version}</option>)}</select></label>;}
 return <div className="space-y-4"><button type="button" disabled={command.busy||command.uncertain} className="rounded border px-3 py-2" onClick={()=>{if(dirty)setConfirmRefresh(true);else{setReview(null);setContent(null);setNonce(n=>n+1);}}}>{t.refresh}</button>
 {confirmRefresh&&<div role="alert" className="space-x-2 rounded border border-amber-600 p-3"><p>{t.unsavedWarning}</p><button type="button" className="rounded border px-3 py-2" onClick={()=>setConfirmRefresh(false)}>{t.keepEditing}</button><button type="button" className="rounded border px-3 py-2" onClick={()=>{setConfirmRefresh(false);setReview(null);setContent(null);setNonce(n=>n+1);}}>{t.discardEdits}</button></div>}
 {failed?<p role="alert">{t.error}</p>:!review||!content?<p role="status">{t.loading}</p>:<>
 <p>{t.baseline}: {review.underwriting_version} · {t.revision}: {review.revision} · {review.status==='submitted'?t.submitted:t.draft}</p>
 {review.underwriting_version!==review.current_underwriting_version&&<p role="alert">{t.stale}</p>}{!review.can_manage&&<p>{t.readonly}</p>}
 {!docContext&&<p>{t.chooseContext}</p>}
 {docContext&&!evidence.length&&<div className="space-y-2"><p>{t.none} {t.uploadHint}</p>{!dirty&&<a className="inline-block rounded border px-3 py-2 underline focus-visible:outline focus-visible:outline-2" href={`/${lang}/app/documents`}>{t.documentsLink}</a>}</div>}
 <form onSubmit={e=>{e.preventDefault();if(!disabled)send('save');}} className="space-y-4"><fieldset disabled={disabled} className="space-y-4"><legend className="font-semibold">{t.title}</legend>
 <div className="grid gap-4 md:grid-cols-3">{content.checklist.map((item,i)=><div key={item.code} className="space-y-2 rounded border p-3"><h3 className="font-semibold">{t[item.code as 'legal'|'financial'|'technical']}</h3><label>{t.status}<select className="block w-full rounded border p-2" value={item.status} onChange={e=>mutate({...content,checklist:content.checklist.map((x,j)=>j===i?{...x,status:e.target.value as 'pending'|'satisfied'}:x)})}><option value="pending">{t.pending}</option><option value="satisfied">{t.satisfied}</option></select></label>{versions(item.evidence_version_ids,ids=>mutate({...content,checklist:content.checklist.map((x,j)=>j===i?{...x,evidence_version_ids:ids}:x)}),`${t.evidence}: ${t[item.code as 'legal'|'financial'|'technical']}`)}</div>)}</div>
 <h3 className="font-semibold">{t.findings}</h3>{content.findings.map((finding,i)=><div key={finding.finding_id} className="grid gap-3 rounded border p-3 sm:grid-cols-2">
 <label>{t.summary}<textarea required maxLength={2000} className="block w-full rounded border p-2" value={finding.summary} onChange={e=>mutate({...content,findings:content.findings.map((x,j)=>j===i?{...x,summary:e.target.value}:x)})}/></label>
 <label>{t.severity}<select disabled={review.findings.some(x=>x.finding_id===finding.finding_id)} className="block w-full rounded border p-2" value={finding.severity} onChange={e=>mutate({...content,findings:content.findings.map((x,j)=>j===i?{...x,severity:e.target.value as 'blocking'|'advisory'}:x)})}><option value="blocking">{t.blocking}</option><option value="advisory">{t.advisory}</option></select></label>
 <label>{t.status}<select className="block w-full rounded border p-2" value={finding.status} onChange={e=>mutate({...content,findings:content.findings.map((x,j)=>j!==i?x:e.target.value==='resolved'?{...x,status:'resolved',resolution:'resolution'in x?x.resolution:''}:{finding_id:x.finding_id,severity:x.severity,status:'open',summary:x.summary,evidence_version_ids:x.evidence_version_ids})})}><option value="open">{t.open}</option><option value="resolved">{t.resolved}</option></select></label>
 {finding.status==='resolved'&&<label>{t.resolution}<textarea required maxLength={2000} className="block w-full rounded border p-2" value={finding.resolution} onChange={e=>mutate({...content,findings:content.findings.map((x,j)=>j===i&&x.status==='resolved'?{...x,resolution:e.target.value}:x)})}/></label>}
 {versions(finding.evidence_version_ids,ids=>mutate({...content,findings:content.findings.map((x,j)=>j===i?{...x,evidence_version_ids:ids}:x)}),`${t.evidence}: ${t.summary} ${i+1}`)}
 </div>)}<button type="button" disabled={content.findings.length>=128} className="rounded border px-3 py-2" onClick={()=>mutate({...content,findings:[...content.findings,{finding_id:crypto.randomUUID(),severity:'blocking',status:'open',summary:'',evidence_version_ids:[]}]})}>{t.add}</button>
 </fieldset><button disabled={disabled} className="rounded bg-slate-900 px-4 py-2 text-white">{t.save}</button>
 <button type="button" disabled={disabled||dirty||!review.can_submit||!review.ready_for_review} className="ms-3 rounded bg-blue-700 px-4 py-2 text-white" onClick={()=>send('submit')}>{t.submit}</button>{review.status!=='submitted'&&!review.ready_for_review&&<p>{t.notReady}</p>}
 </form>
 <CustomerAirpropAcquisition contextId={native.context_id} workspaceId={native.workspace_id} opportunityId={native.opportunity_id} diligenceCaseId={caseId} documentContextId={docContext} lang={lang} refreshToken={nonce+reloadParent}/>
 </>}
 {command.uncertain&&<button type="button" disabled={command.busy||command.blocked||command.recovering} className="rounded bg-slate-900 px-4 py-2 text-white" onClick={()=>command.pending.current&&void command.send(command.pending.current)}>{t.retry}</button>}<p role="status" aria-live="polite">{command.message?t[command.message]:''}</p>
 </div>;
}
