'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {Language} from '@/types';
type Choices={properties:{id:string;name:string}[];buildings:{id:string;property_id:string;name:string}[];building_required:boolean};
const copy={
 en:{open:'Register equipment',close:'Close',property:'Property',building:'Building',whole:'Whole property',category:'Equipment type',code:'Inventory code',name:'Equipment name',save:'Register',loading:'Loading available locations…',empty:'No active property is available in this context.',error:'Registration failed. Refresh and check your permissions.',mfa:'Critical equipment requires MFA and critical asset management permission.',success:'Equipment registered. Refresh maintenance plans to use it.',note:'Equipment starts in the planned lifecycle. Elevator and fire safety equipment require elevated permission and MFA.',categories:{ventilation:'Ventilation',pump:'Pump',elevator:'Elevator',fire_safety:'Fire safety',other:'Other equipment'}},
 ro:{open:'Înregistrează echipament',close:'Închide',property:'Proprietate',building:'Clădire',whole:'Întreaga proprietate',category:'Tipul echipamentului',code:'Cod de inventar',name:'Numele echipamentului',save:'Înregistrează',loading:'Se încarcă locațiile disponibile…',empty:'Nu există proprietăți active disponibile în acest context.',error:'Înregistrarea nu a reușit. Reîncarcă și verifică permisiunile.',mfa:'Echipamentul critic necesită MFA și permisiune de administrare a activelor critice.',success:'Echipament înregistrat. Reîncarcă programele de mentenanță pentru a-l folosi.',note:'Echipamentul începe în etapa planificată. Lifturile și echipamentele de incendiu necesită permisiune suplimentară și MFA.',categories:{ventilation:'Ventilație',pump:'Pompă',elevator:'Lift',fire_safety:'Siguranță la incendiu',other:'Alt echipament'}},
 fa:{open:'ثبت تجهیز جدید',close:'بستن',property:'ملک',building:'ساختمان',whole:'کل ملک',category:'نوع تجهیز',code:'کد موجودی',name:'نام تجهیز',save:'ثبت تجهیز',loading:'در حال دریافت مکان‌های مجاز…',empty:'ملک فعال و مجازی در این زمینه موجود نیست.',error:'ثبت انجام نشد؛ صفحه را بازخوانی و مجوز نقش را بررسی کنید.',mfa:'ثبت تجهیزات حیاتی به ورود دومرحله‌ای و مجوز مدیریت تجهیزات حیاتی نیاز دارد.',success:'تجهیز ثبت شد؛ برای استفاده در برنامهٔ نگهداری، برنامه‌ها را بازخوانی کنید.',note:'تجهیز با وضعیت برنامه‌ریزی‌شده ثبت می‌شود. ثبت آسانسور و تجهیزات آتش‌نشانی به مجوز ویژه و ورود دومرحله‌ای نیاز دارد.',categories:{ventilation:'تهویه',pump:'پمپ',elevator:'آسانسور',fire_safety:'ایمنی آتش‌نشانی',other:'سایر تجهیزات'}},
};
export function EquipmentRegistrationPanel({lang,contextId,onRegistered}:{lang:Language;contextId:string;onRegistered:()=>void}){return <Registration key={contextId} lang={lang} contextId={contextId} onRegistered={onRegistered}/>;}
function Registration({lang,contextId,onRegistered}:{lang:Language;contextId:string;onRegistered:()=>void}){
 const t=copy[lang];const [open,setOpen]=useState(false),[choices,setChoices]=useState<Choices|null>(null),[property,setProperty]=useState(''),[building,setBuilding]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const abort=useRef<AbortController|null>(null);
 useEffect(()=>{const controller=new AbortController();abort.current=controller;return()=>controller.abort();},[]);
 useEffect(()=>{if(!open)return;const controller=new AbortController();fetch(`/api/customer/v1/assets/registration?context_id=${encodeURIComponent(contextId)}`,{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();const data:Choices=await response.json();if(!controller.signal.aborted){setChoices(data);setProperty(data.properties.length===1?data.properties[0].id:'');setBuilding('');}}).catch(()=>{if(!controller.signal.aborted)setMessage(t.error);});return()=>controller.abort();},[open,contextId,t.error]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const mutationAbort=abort.current;if(!mutationAbort)return;const form=event.currentTarget;const fields=new FormData(form);setBusy(true);setMessage('');try{const response=await fetch('/api/customer/v1/assets/registration',{method:'POST',signal:mutationAbort.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({context_id:contextId,property_id:property,building_id:building||null,category_code:fields.get('category'),asset_code:fields.get('code'),name:fields.get('name')})});const data=await response.json();if(!response.ok)throw Error(data.error?.code==='MFA_REQUIRED'?t.mfa:t.error);if(!mutationAbort.signal.aborted){form.reset();setMessage(t.success);onRegistered();}}catch(error){if(!mutationAbort.signal.aborted)setMessage(error instanceof Error?error.message:t.error);}finally{if(!mutationAbort.signal.aborted)setBusy(false);}}
 return <section className="rounded-xl border border-teal-200 bg-white p-4" dir={lang==='fa'?'rtl':'ltr'}><button type="button" disabled={busy} onClick={()=>{setMessage('');setOpen(value=>!value);}} aria-expanded={open} className="rounded-lg bg-teal-700 px-4 py-2 font-semibold text-white disabled:opacity-50">{open?t.close:t.open}</button>{open&&<div className="mt-4 space-y-3"><h2 className="text-lg font-bold">{t.open}</h2><p className="text-sm text-slate-600">{t.note}</p>{message&&<p role="status">{message}</p>}{!choices?(!message&&<p>{t.loading}</p>):!choices.properties.length?<p>{t.empty}</p>:<form onSubmit={save} className="grid gap-3 md:grid-cols-2"><label>{t.property}<select required value={property} disabled={busy} onChange={event=>{setProperty(event.target.value);setBuilding('');}} className="block w-full rounded border p-2"><option value="">—</option>{choices.properties.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t.building}<select required={choices.building_required} value={building} disabled={busy||!property} onChange={event=>setBuilding(event.target.value)} className="block w-full rounded border p-2"><option value="">{choices.building_required?'—':t.whole}</option>{choices.buildings.filter(item=>item.property_id===property).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t.category}<select name="category" disabled={busy} className="block w-full rounded border p-2">{Object.entries(t.categories).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>{t.code}<input name="code" required maxLength={64} disabled={busy} className="block w-full rounded border p-2"/></label><label>{t.name}<input name="name" required maxLength={255} disabled={busy} className="block w-full rounded border p-2"/></label><div className="self-end"><button disabled={busy} className="rounded-lg bg-teal-700 px-4 py-2 font-semibold text-white disabled:opacity-50">{t.save}</button></div></form>}</div>}</section>;
}
