'use client';
import {useEffect,useState,useRef} from 'react';
import type {Language} from '@/types';
import {localizedMaintenanceText, maintenanceTemplateFor, suggestedMaintenancePlans} from '@/lib/customer/maintenance-defaults';
type Plan={id:string;revision:number;name:string;asset_id:string;asset_name:string;vendor_id:string;vendor_name:string;calendar_anchor:string;calendar_unit:string;calendar_every:number;calendar_enabled:boolean;next_due_on:string;checklist_template:string[];history:{due_on:string;work_order_no:number;status:string}[]};
type Data={plans:Plan[];assets:{id:string;name:string;asset_code:string;category_code:string}[];vendors:{id:string;name:string}[]};
const statusLabels:Record<Language,Record<string,string>>={en:{draft:'Draft',scheduled:'Scheduled',assigned:'Assigned',in_progress:'In progress',blocked:'Blocked',completed:'Completed',verified:'Verified',cancelled:'Cancelled'},ro:{draft:'Proiect',scheduled:'Programat',assigned:'Alocat',in_progress:'În lucru',blocked:'Blocat',completed:'Finalizat',verified:'Verificat',cancelled:'Anulat'},fa:{draft:'پیش‌نویس',scheduled:'زمان‌بندی‌شده',assigned:'واگذارشده',in_progress:'در حال اجرا',blocked:'متوقف',completed:'انجام‌شده',verified:'تأییدشده',cancelled:'لغوشده'}};
const copy={
 en:{title:'Recurring preventive maintenance',note:'Select equipment to see programs for its category. Newly registered equipment appears after refresh. Set a contractor and calendar before saving; issuing due drafts is manual.',preset:'Suggested program',custom:'Custom program',presetNote:'Suggestions depend on the equipment category; use a custom plan if none match. Intervals are editable and are not statutory inspection frequencies.',name:'Plan name',asset:'Equipment',vendor:'Approved contractor',anchor:'First due date',unit:'Period',every:'Every',days:'Days',weeks:'Weeks',months:'Months',years:'Years',checklist:'Required checklist (one item per line)',enabled:'Enabled',save:'Save plan',edit:'Edit',cancel:'Cancel edit',generate:'Issue due draft',history:'Issued occurrences',due:'Next due',empty:'No recurring plans visible.',loading:'Loading plans…',error:'Could not complete the operation. Check permissions, module activation and MFA, then refresh.',conflict:'This plan changed. Refresh before editing again.',refresh:'Refresh',noAssets:'To configure a plan, activate maintenance and use a role allowed to manage work orders for an active asset.',limits:'Displays up to 200 plans and 500 equipment / contractor choices. Calendar and equipment are fixed after creation; disable the old plan and create another to change them.',success:'Saved.',disabled:'Disabled; history retained'},
 ro:{title:'Mentenanță preventivă periodică',note:'Selectează echipamentul pentru programele recomandate categoriei sale. Echipamentele noi apar după reîncărcare. Alege furnizorul și calendarul înainte de salvare; emiterea proiectelor scadente este manuală.',preset:'Program recomandat',custom:'Program personalizat',presetNote:'Recomandările depind de categoria echipamentului; folosește un program personalizat dacă nu există. Intervalele nu reprezintă obligații legale.',name:'Numele planului',asset:'Echipament',vendor:'Furnizor aprobat',anchor:'Prima scadență',unit:'Perioadă',every:'La fiecare',days:'Zile',weeks:'Săptămâni',months:'Luni',years:'Ani',checklist:'Listă obligatorie (un element pe rând)',enabled:'Activ',save:'Salvează planul',edit:'Editează',cancel:'Anulează editarea',generate:'Emite proiectul scadent',history:'Scadențe emise',due:'Următoarea scadență',empty:'Nu există planuri periodice vizibile.',loading:'Se încarcă planurile…',error:'Operația nu a reușit. Verifică permisiunile, activarea modulului și MFA, apoi reîncarcă.',conflict:'Planul s-a modificat. Reîncarcă înainte de editare.',refresh:'Reîncarcă',noAssets:'Activează mentenanța și folosește un rol cu drept de administrare a ordinelor pentru un activ disponibil.',limits:'Sunt afișate maximum 200 de planuri și 500 de echipamente / furnizori. Calendarul și echipamentul sunt fixe după creare; dezactivează planul vechi și creează altul pentru a le modifica.',success:'Salvat.',disabled:'Dezactivat; istoricul este păstrat'},
 fa:{title:'برنامهٔ ثابت تعمیر و نگهداری',note:'تجهیز را انتخاب کنید تا برنامه‌های مربوط به دستهٔ آن پیشنهاد شود. تجهیز تازه‌ثبت‌شده پس از بازخوانی ظاهر می‌شود. پیش از ذخیره، پیمانکار و دوره را مشخص کنید؛ صدور پیش‌نویس سررسید دستی است.',preset:'برنامهٔ پیشنهادی',custom:'برنامهٔ سفارشی',presetNote:'پیشنهادها بر پایهٔ دستهٔ تجهیز هستند؛ اگر پیشنهادی نبود برنامهٔ سفارشی بسازید. دوره‌ها قابل تغییرند و الزام قانونی محسوب نمی‌شوند.',name:'نام برنامه',asset:'تجهیز',vendor:'پیمانکار تأییدشده',anchor:'اولین سررسید',unit:'دوره',every:'هر',days:'روز',weeks:'هفته',months:'ماه',years:'سال',checklist:'چک‌لیست الزامی؛ هر مورد در یک خط',enabled:'فعال',save:'ذخیره برنامه',edit:'ویرایش',cancel:'انصراف از ویرایش',generate:'صدور پیش‌نویس سررسید',history:'نوبت‌های صادرشده',due:'سررسید بعدی',empty:'برنامهٔ دوره‌ای قابل مشاهده‌ای وجود ندارد.',loading:'در حال دریافت برنامه‌ها…',error:'عملیات انجام نشد. مجوز نقش، فعال‌سازی ماژول و تأیید دومرحله‌ای را بررسی و صفحه را بازخوانی کنید.',conflict:'برنامه تغییر کرده است؛ پیش از ویرایش دوباره بازخوانی کنید.',refresh:'بازخوانی',noAssets:'برای تعریف برنامه، ماژول نگهداری را فعال کنید و از نقش دارای مجوز مدیریت دستورکار برای تجهیز فعال استفاده کنید.',limits:'حداکثر ۲۰۰ برنامه و ۵۰۰ تجهیز یا پیمانکار نمایش داده می‌شود. تجهیز و دوره پس از ثبت ثابت می‌مانند؛ برای تغییر آن‌ها برنامه قبلی را غیرفعال و برنامه جدید ایجاد کنید.',success:'ذخیره شد.',disabled:'غیرفعال؛ سوابق محفوظ است'},
};
// Remount on context change so an old workspace can never populate the new form.
export function PreventiveMaintenancePanel({lang,contextId}:{lang:Language;contextId:string}){return <Plans key={contextId} lang={lang} contextId={contextId}/>}
function Plans({lang,contextId}:{lang:Language;contextId:string}){
 const draftId=useRef<string|null>(null);
 const t=copy[lang];const[data,setData]=useState<Data|null>(null),[nonce,setNonce]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[editing,setEditing]=useState<Plan|null>(null),[selectedCode,setSelectedCode]=useState(''),[selectedAsset,setSelectedAsset]=useState('');
 const template=maintenanceTemplateFor(selectedCode);
 const suggestions=suggestedMaintenancePlans(data?.assets.find(a=>a.id===(editing?.asset_id??selectedAsset))?.category_code??'');
 const displayedSuggestions=template&&editing&&!suggestions.includes(template)?[...suggestions,template]:suggestions;
 useEffect(()=>{const abort=new AbortController();fetch(`/api/customer/v1/maintenance-plans?context_id=${encodeURIComponent(contextId)}`,{cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw Error();const d=await r.json();if(!abort.signal.aborted)setData(d)}).catch(()=>{if(!abort.signal.aborted)setMessage(t.error)});return()=>abort.abort()},[contextId,nonce,t.error]);
 async function mutate(body:Record<string,unknown>){setBusy(true);setMessage('');try{const r=await fetch('/api/customer/v1/maintenance-plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,context_id:contextId})});if(!r.ok)throw Error(r.status===409?t.conflict:t.error);draftId.current=null;setEditing(null);setSelectedCode('');setSelectedAsset('');setMessage(t.success);setData(null);setNonce(n=>n+1)}catch(e){setMessage(e instanceof Error?e.message:t.error)}finally{setBusy(false)}}
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Bucharest',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 return <section className="space-y-4 rounded-2xl border bg-white p-5" dir={lang==='fa'?'rtl':'ltr'}><h2 className="text-xl font-bold">{t.title}</h2><p>{t.note}</p><p className="text-xs text-slate-500">{t.limits}</p><button type="button" disabled={busy} onClick={()=>{setEditing(null);setSelectedCode('');setSelectedAsset('');setMessage('');setData(null);setNonce(n=>n+1)}} className="rounded border px-3 py-2">{t.refresh}</button>{message&&<p role="status">{message}</p>}{!data?<p>{message?null:t.loading}</p>:<>
 {data.assets.length>0?<form key={editing?.id??`new-${nonce}-${selectedAsset}-${selectedCode}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate({action:'save',id:editing?.id??(draftId.current??=crypto.randomUUID()),revision:editing?.revision??0,name:template?.code??f.get('name'),asset_id:editing?.asset_id??selectedAsset,vendor_id:f.get('vendor'),anchor:editing?.calendar_anchor??f.get('anchor'),unit:editing?.calendar_unit??f.get('unit'),every:editing?.calendar_every??Number(f.get('every')),enabled:f.get('enabled')==='on',checklist:template?template.steps.map(step=>step.code):String(f.get('checklist')??'').split('\n').map(s=>s.trim()).filter(Boolean)})}} className="grid gap-3 md:grid-cols-2">
 <label>{t.preset}<select value={selectedCode} disabled={!!editing||!selectedAsset} onChange={e=>setSelectedCode(e.target.value)} className="block w-full rounded border p-2"><option value="">{t.custom}</option>{displayedSuggestions.map(p=><option key={p.code} value={p.code}>{p.title[lang]}</option>)}</select><span className="block text-xs text-slate-500">{t.presetNote}</span></label>
 <label>{t.name}{template?<input required readOnly value={template.title[lang]} className="block w-full rounded border bg-slate-50 p-2"/>:<input name="name" required maxLength={200} defaultValue={editing?.name} className="block w-full rounded border p-2"/>}</label>
 <label>{t.asset}<select required disabled={!!editing} value={editing?.asset_id??selectedAsset} onChange={e=>{setSelectedAsset(e.target.value);const matches=suggestedMaintenancePlans(data.assets.find(a=>a.id===e.target.value)?.category_code??'');setSelectedCode(matches.length===1?matches[0].code:'')}} className="block w-full rounded border p-2"><option value="">—</option>{data.assets.map(a=><option key={a.id} value={a.id}>{a.name} · {a.asset_code}</option>)}</select></label>
 <label>{t.vendor}<select name="vendor" required defaultValue={editing?.vendor_id??''} className="block w-full rounded border p-2"><option value="">—</option>{data.vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
 <label>{t.anchor}<input name="anchor" type="date" required disabled={!!editing} defaultValue={editing?.calendar_anchor} className="block w-full rounded border p-2"/></label>
 <label>{t.every}<input name="every" type="number" required min={1} max={120} disabled={!!editing} defaultValue={editing?.calendar_every??template?.suggestedEvery??1} className="block w-full rounded border p-2"/></label>
 <label>{t.unit}<select name="unit" disabled={!!editing} defaultValue={editing?.calendar_unit??template?.suggestedUnit??'months'} className="block w-full rounded border p-2">{(['days','weeks','months','years'] as const).map(u=><option key={u} value={u}>{t[u]}</option>)}</select></label>
 <label className="md:col-span-2">{t.checklist}<textarea name="checklist" readOnly={!!template} value={template?template.steps.map(s=>s.label[lang]).join('\n'):undefined} defaultValue={template?undefined:editing?.checklist_template.join('\n')} className="block w-full rounded border bg-white p-2 read-only:bg-slate-50"/></label>
 <label><input name="enabled" type="checkbox" defaultChecked={editing?.calendar_enabled??true}/> {t.enabled}</label><div><button disabled={busy} className="rounded bg-teal-700 px-4 py-2 text-white">{t.save}</button>{editing&&<button type="button" disabled={busy} onClick={()=>{setEditing(null);setSelectedCode('')}} className="ms-3 rounded border px-3 py-2">{t.cancel}</button>}</div></form>:<p>{t.noAssets}</p>}
 {!data.plans.length&&<p>{t.empty}</p>}{data.plans.map(p=><article key={p.id} className="space-y-2 rounded border p-3"><h3 className="font-bold">{localizedMaintenanceText(p.name,lang)}</h3><p>{p.asset_name} · {p.vendor_name}</p><p>{p.calendar_enabled?`${t.due}: ${p.next_due_on}`:t.disabled}</p>{data.assets.some(a=>a.id===p.asset_id)&&<div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>{setSelectedCode(maintenanceTemplateFor(p.name)?.code??'');setSelectedAsset(p.asset_id);setEditing(p)}} className="rounded-lg border border-teal-600 bg-white px-3 py-2 text-sm font-semibold text-teal-800 hover:bg-teal-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 disabled:opacity-50">{t.edit}</button><button type="button" disabled={busy||!p.calendar_enabled||p.next_due_on>today} onClick={()=>void mutate({action:'generate',plan_id:p.id,due_on:p.next_due_on})} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-semibold text-white hover:bg-teal-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-500">{t.generate}</button></div>}<details><summary className="cursor-pointer font-medium text-teal-800">{t.history} ({p.history.length})</summary>{p.history.map(h=><p key={h.due_on}>{h.due_on} · #{h.work_order_no} · {statusLabels[lang][h.status]??h.status}</p>)}</details></article>)}
 </>}</section>;
}
