'use client';
import {useEffect,useState,useRef} from 'react';
import type {Language} from '@/types';
type Plan={id:string;revision:number;name:string;asset_id:string;asset_name:string;vendor_id:string;vendor_name:string;calendar_anchor:string;calendar_unit:string;calendar_every:number;calendar_enabled:boolean;next_due_on:string;checklist_template:string[];history:{due_on:string;work_order_no:number;status:string}[]};
type Data={plans:Plan[];assets:{id:string;name:string;asset_code:string}[];vendors:{id:string;name:string}[]};
const statusLabels:Record<Language,Record<string,string>>={en:{draft:'Draft',scheduled:'Scheduled',assigned:'Assigned',in_progress:'In progress',blocked:'Blocked',completed:'Completed',verified:'Verified',cancelled:'Cancelled'},ro:{draft:'Proiect',scheduled:'Programat',assigned:'Alocat',in_progress:'În lucru',blocked:'Blocat',completed:'Finalizat',verified:'Verificat',cancelled:'Anulat'},fa:{draft:'پیش‌نویس',scheduled:'زمان‌بندی‌شده',assigned:'واگذارشده',in_progress:'در حال اجرا',blocked:'متوقف',completed:'انجام‌شده',verified:'تأییدشده',cancelled:'لغوشده'}};
const copy={
 en:{title:'Recurring preventive maintenance',note:'Set a fixed calendar for each asset and approved contractor. Issue each due occurrence as a draft; approval and execution use the existing work-order workflow. Issuing is manual in this version.',name:'Plan name',asset:'Equipment',vendor:'Approved contractor',anchor:'First due date',unit:'Period',every:'Every',days:'Days',weeks:'Weeks',months:'Months',years:'Years',checklist:'Required checklist (one item per line)',enabled:'Enabled',save:'Save plan',edit:'Edit',cancel:'Cancel edit',generate:'Issue due draft',history:'Issued occurrences',due:'Next due',empty:'No recurring plans visible.',loading:'Loading plans…',error:'Could not complete the operation. Check permissions, module activation and MFA, then refresh.',conflict:'This plan changed. Refresh before editing again.',refresh:'Refresh',noAssets:'To configure a plan, activate maintenance and use a role allowed to manage work orders for an active asset.',limits:'Displays up to 200 plans and 500 equipment / contractor choices. Calendar and equipment are fixed after creation; disable the old plan and create another to change them.',success:'Saved.',disabled:'Disabled; history retained'},
 ro:{title:'Mentenanță preventivă periodică',note:'Definește un calendar fix pentru fiecare activ și furnizor aprobat. Emite fiecare scadență ca proiect; aprobarea și execuția folosesc fluxul existent al ordinelor de lucru. Emiterea este manuală în această versiune.',name:'Numele planului',asset:'Echipament',vendor:'Furnizor aprobat',anchor:'Prima scadență',unit:'Perioadă',every:'La fiecare',days:'Zile',weeks:'Săptămâni',months:'Luni',years:'Ani',checklist:'Listă obligatorie (un element pe rând)',enabled:'Activ',save:'Salvează planul',edit:'Editează',cancel:'Anulează editarea',generate:'Emite proiectul scadent',history:'Scadențe emise',due:'Următoarea scadență',empty:'Nu există planuri periodice vizibile.',loading:'Se încarcă planurile…',error:'Operația nu a reușit. Verifică permisiunile, activarea modulului și MFA, apoi reîncarcă.',conflict:'Planul s-a modificat. Reîncarcă înainte de editare.',refresh:'Reîncarcă',noAssets:'Activează mentenanța și folosește un rol cu drept de administrare a ordinelor pentru un activ disponibil.',limits:'Sunt afișate maximum 200 de planuri și 500 de echipamente / furnizori. Calendarul și echipamentul sunt fixe după creare; dezactivează planul vechi și creează altul pentru a le modifica.',success:'Salvat.',disabled:'Dezactivat; istoricul este păstrat'},
 fa:{title:'برنامهٔ ثابت تعمیر و نگهداری',note:'برای هر تجهیز و پیمانکار تأییدشده، دورهٔ ثابت تعریف کنید. هر نوبت سررسیدشده به‌صورت پیش‌نویس دستورکار صادر می‌شود؛ تأیید و اجرا در گردش‌کار موجود انجام می‌شود. صدور در این نسخه دستی است.',name:'نام برنامه',asset:'تجهیز',vendor:'پیمانکار تأییدشده',anchor:'اولین سررسید',unit:'دوره',every:'هر',days:'روز',weeks:'هفته',months:'ماه',years:'سال',checklist:'چک‌لیست الزامی؛ هر مورد در یک خط',enabled:'فعال',save:'ذخیره برنامه',edit:'ویرایش',cancel:'انصراف از ویرایش',generate:'صدور پیش‌نویس سررسید',history:'نوبت‌های صادرشده',due:'سررسید بعدی',empty:'برنامهٔ دوره‌ای قابل مشاهده‌ای وجود ندارد.',loading:'در حال دریافت برنامه‌ها…',error:'عملیات انجام نشد. مجوز نقش، فعال‌سازی ماژول و تأیید دومرحله‌ای را بررسی و صفحه را بازخوانی کنید.',conflict:'برنامه تغییر کرده است؛ پیش از ویرایش دوباره بازخوانی کنید.',refresh:'بازخوانی',noAssets:'برای تعریف برنامه، ماژول نگهداری را فعال کنید و از نقش دارای مجوز مدیریت دستورکار برای تجهیز فعال استفاده کنید.',limits:'حداکثر ۲۰۰ برنامه و ۵۰۰ تجهیز یا پیمانکار نمایش داده می‌شود. تجهیز و دوره پس از ثبت ثابت می‌مانند؛ برای تغییر آن‌ها برنامه قبلی را غیرفعال و برنامه جدید ایجاد کنید.',success:'ذخیره شد.',disabled:'غیرفعال؛ سوابق محفوظ است'},
};
// Remount on context change so an old workspace can never populate the new form.
export function PreventiveMaintenancePanel({lang,contextId}:{lang:Language;contextId:string}){return <Plans key={contextId} lang={lang} contextId={contextId}/>}
function Plans({lang,contextId}:{lang:Language;contextId:string}){
 const draftId=useRef<string|null>(null);
 const t=copy[lang];const[data,setData]=useState<Data|null>(null),[nonce,setNonce]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[editing,setEditing]=useState<Plan|null>(null);
 useEffect(()=>{const abort=new AbortController();fetch(`/api/customer/v1/maintenance-plans?context_id=${encodeURIComponent(contextId)}`,{cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw Error();const d=await r.json();if(!abort.signal.aborted)setData(d)}).catch(()=>{if(!abort.signal.aborted)setMessage(t.error)});return()=>abort.abort()},[contextId,nonce,t.error]);
 async function mutate(body:Record<string,unknown>){setBusy(true);setMessage('');try{const r=await fetch('/api/customer/v1/maintenance-plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,context_id:contextId})});if(!r.ok)throw Error(r.status===409?t.conflict:t.error);draftId.current=null;setEditing(null);setMessage(t.success);setData(null);setNonce(n=>n+1)}catch(e){setMessage(e instanceof Error?e.message:t.error)}finally{setBusy(false)}}
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Bucharest',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 return <section className="space-y-4 rounded-2xl border bg-white p-5" dir={lang==='fa'?'rtl':'ltr'}><h2 className="text-xl font-bold">{t.title}</h2><p>{t.note}</p><p className="text-xs text-slate-500">{t.limits}</p><button type="button" disabled={busy} onClick={()=>{setEditing(null);setMessage('');setData(null);setNonce(n=>n+1)}} className="rounded border px-3 py-2">{t.refresh}</button>{message&&<p role="status">{message}</p>}{!data?<p>{message?null:t.loading}</p>:<>
 {data.assets.length>0?<form key={editing?.id??`new-${nonce}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate({action:'save',id:editing?.id??(draftId.current??=crypto.randomUUID()),revision:editing?.revision??0,name:f.get('name'),asset_id:editing?.asset_id??f.get('asset'),vendor_id:f.get('vendor'),anchor:editing?.calendar_anchor??f.get('anchor'),unit:editing?.calendar_unit??f.get('unit'),every:editing?.calendar_every??Number(f.get('every')),enabled:f.get('enabled')==='on',checklist:String(f.get('checklist')??'').split('\n').map(s=>s.trim()).filter(Boolean)})}} className="grid gap-3 md:grid-cols-2">
 <label>{t.name}<input name="name" required maxLength={200} defaultValue={editing?.name} className="block w-full rounded border p-2"/></label>
 <label>{t.asset}<select name="asset" required disabled={!!editing} defaultValue={editing?.asset_id??''} className="block w-full rounded border p-2"><option value="">—</option>{data.assets.map(a=><option key={a.id} value={a.id}>{a.name} · {a.asset_code}</option>)}</select></label>
 <label>{t.vendor}<select name="vendor" required defaultValue={editing?.vendor_id??''} className="block w-full rounded border p-2"><option value="">—</option>{data.vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
 <label>{t.anchor}<input name="anchor" type="date" required disabled={!!editing} defaultValue={editing?.calendar_anchor} className="block w-full rounded border p-2"/></label>
 <label>{t.every}<input name="every" type="number" required min={1} max={120} disabled={!!editing} defaultValue={editing?.calendar_every??1} className="block w-full rounded border p-2"/></label>
 <label>{t.unit}<select name="unit" disabled={!!editing} defaultValue={editing?.calendar_unit??'months'} className="block w-full rounded border p-2">{(['days','weeks','months','years'] as const).map(u=><option key={u} value={u}>{t[u]}</option>)}</select></label>
 <label className="md:col-span-2">{t.checklist}<textarea name="checklist" defaultValue={editing?.checklist_template.join('\n')} className="block w-full rounded border p-2"/></label>
 <label><input name="enabled" type="checkbox" defaultChecked={editing?.calendar_enabled??true}/> {t.enabled}</label><div><button disabled={busy} className="rounded bg-teal-700 px-4 py-2 text-white">{t.save}</button>{editing&&<button type="button" disabled={busy} onClick={()=>setEditing(null)} className="ms-3">{t.cancel}</button>}</div></form>:<p>{t.noAssets}</p>}
 {!data.plans.length&&<p>{t.empty}</p>}{data.plans.map(p=><article key={p.id} className="space-y-2 rounded border p-3"><h3 className="font-bold">{p.name}</h3><p>{p.asset_name} · {p.vendor_name}</p><p>{p.calendar_enabled?`${t.due}: ${p.next_due_on}`:t.disabled}</p>{data.assets.some(a=>a.id===p.asset_id)&&<div className="flex gap-3"><button disabled={busy} onClick={()=>setEditing(p)}>{t.edit}</button><button disabled={busy||!p.calendar_enabled||p.next_due_on>today} onClick={()=>void mutate({action:'generate',plan_id:p.id,due_on:p.next_due_on})}>{t.generate}</button></div>}<details><summary>{t.history} ({p.history.length})</summary>{p.history.map(h=><p key={h.due_on}>{h.due_on} · #{h.work_order_no} · {statusLabels[lang][h.status]??h.status}</p>)}</details></article>)}
 </>}</section>;
}
