import { createHash } from 'node:crypto';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { strToU8, zipSync } from 'fflate';

export const EXPORT_REPORT_CODES = ['trial_balance','unit_charges','receivables_collections','bank_reconciliation','supplier_invoices_payments','meter_allocation_evidence','governance_audit_trail'] as const;
export const EXPORT_FORMATS = ['pdf','xlsx','csv'] as const;
export type ExportReportCode=(typeof EXPORT_REPORT_CODES)[number];
export type ExportFormat=(typeof EXPORT_FORMATS)[number];
export const MAX_EXPORT_BYTES=5*1024*1024;
type Pack={export_pack_id:string;source_sha256:string;manifest_sha256:string;source_snapshot:Record<string,unknown>};
const labels:Record<ExportReportCode,string>={trial_balance:'Balanta de verificare',unit_charges:'Registrul cotelor si repartizarilor',receivables_collections:'Registrul creantelor si incasarilor',bank_reconciliation:'Raport de reconciliere bancara',supplier_invoices_payments:'Registrul facturilor furnizorilor si platilor',meter_allocation_evidence:'Dovezi contoare si repartizare',governance_audit_trail:'Registrul aprobarilor si auditului'};
function safeText(v:unknown){return String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/^[=+\-@]/,"'").slice(0,2000)}
function xml(v:unknown){return safeText(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function rows(pack:Pack,code:ExportReportCode):string[][]{const s=pack.source_snapshot||{};const counts=(s.register_counts||{}) as Record<string,unknown>;return [['Camp','Valoare'],['Raport',labels[code]],['Contract','CLADORA-P2-EXPORT-001'],['Pachet export',pack.export_pack_id],['Perioada',`${safeText(s.period_start)} - ${safeText(s.period_end)}`],['SHA-256 sursa',pack.source_sha256],['SHA-256 manifest',pack.manifest_sha256],['Jurnale postate',safeText(counts.posted_journals)],['Facturi emise',safeText(counts.issued_invoices)],['Reconciliari bancare',safeText(counts.bank_sessions)]]}
function csv(data:string[][]){return Buffer.from('\uFEFF'+data.map(r=>r.map(v=>`"${safeText(v).replace(/"/g,'""')}"`).join(',')).join('\r\n')+'\r\n','utf8')}
function col(n:number){let x='';for(n++;n;n=Math.floor((n-1)/26))x=String.fromCharCode(65+(n-1)%26)+x;return x}
function xlsx(data:string[][]){const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${data.map((r,ri)=>`<row r="${ri+1}">${r.map((v,ci)=>`<c r="${col(ci)}${ri+1}" t="inlineStr"><is><t>${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData></worksheet>`;const files:Record<string,Uint8Array>={'[Content_Types].xml':strToU8('<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'),'_rels/.rels':strToU8('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'),'xl/workbook.xml':strToU8('<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Raport" sheetId="1" r:id="rId1"/></sheets></workbook>'),'xl/_rels/workbook.xml.rels':strToU8('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'),'xl/worksheets/sheet1.xml':strToU8(sheet)};return Buffer.from(zipSync(files,{level:6,mtime:new Date('1981-01-01T00:00:00Z')}))}
async function pdf(data:string[][]){const d=await PDFDocument.create();d.setTitle('CLADORA Export');d.setProducer('CLADORA');d.setCreationDate(new Date(0));d.setModificationDate(new Date(0));const font=await d.embedFont(StandardFonts.Helvetica);let p=d.addPage([595,842]),y=800;for(const r of data){const line=r.map(safeText).join(' | ').normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(y<45){p=d.addPage([595,842]);y=800}p.drawText(line.slice(0,105),{x:36,y,size:9,font,color:rgb(0.05,0.12,0.2)});y-=18}return Buffer.from(await d.save({useObjectStreams:false,addDefaultPage:false}))}
export async function renderExportArtifact(pack:Pack,code:ExportReportCode,format:ExportFormat){const data=rows(pack,code);const buffer=format==='csv'?csv(data):format==='xlsx'?xlsx(data):await pdf(data);if(!buffer.length||buffer.length>MAX_EXPORT_BYTES)throw new Error('export_artifact_size_out_of_bounds');return {buffer,sha256:createHash('sha256').update(buffer).digest('hex'),mediaType:format==='pdf'?'application/pdf':format==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv; charset=utf-8',filename:`${code}.stage4.${format}`}}
