begin;

-- Each view uses its own scoped CTE. A CTE from the summary statement cannot
-- be referenced by a later SELECT in PL/pgSQL. Retain the existing role and
-- classification filter unchanged in each statement.
create or replace function documents.get_customer_documents(p_context_id uuid,p_view text default 'documents',p_query text default null,p_status text default null,p_classification text default null,p_from date default null,p_to date default null,p_limit integer default 25,p_offset integer default 0,p_id uuid default null)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog,documents,identity,platform,portfolio,occupancy
as $$
declare x record;v_workspace uuid;v_party uuid;v_resident boolean;v_tenant boolean;v_total bigint;v_rows jsonb;v_summary jsonb;v_detail jsonb;
begin
 if auth.uid() is null then raise exception 'authentication_required' using errcode='42501';end if;
 if coalesce(auth.jwt()->>'aal','aal1')<>'aal2' then raise exception 'mfa_required' using errcode='42501';end if;
 if p_view not in('documents','versions','categories','retention','holds','evidence','links','history')or p_limit<1 or p_limit>100 or p_offset<0 then raise exception 'invalid_query' using errcode='22023';end if;
 if p_classification is not null and p_classification not in('public','internal','confidential','restricted')then raise exception 'invalid_classification' using errcode='22023';end if;
 select g.*,m.id membership_key,m.role_id,r.code role_code,r.name role_name into x from identity.context_grants g join identity.memberships m on m.id=g.membership_id and m.tenant_id=g.tenant_id join identity.roles r on r.id=m.role_id where g.id=p_context_id and m.user_id=auth.uid()and m.status='active'and m.starts_at<=statement_timestamp()and(m.ends_at is null or m.ends_at>statement_timestamp())and g.starts_at<=statement_timestamp()and(g.ends_at is null or g.ends_at>statement_timestamp());
 if not found then raise exception 'customer_context_access_denied' using errcode='42501';end if;
 if lower(x.role_code)not in('association_admin','property_manager','president','censor','owner','tenant_resident')then raise exception 'documents_role_denied' using errcode='42501';end if;
 if not exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id where rp.role_id=x.role_id and rp.effect='allow'and p.code='documents.vault.read')then raise exception 'documents_permission_required' using errcode='42501';end if;
 select w.id into v_workspace from platform.customer_workspaces w where w.tenant_id=x.tenant_id and w.lifecycle_status='ACTIVE'order by w.id limit 1;
 if v_workspace is null or not exists(select 1 from platform.workspace_entitlements e where e.customer_workspace_id=v_workspace and e.entitlement_key='module.documents'and e.valid_from<=statement_timestamp()and(e.valid_until is null or e.valid_until>statement_timestamp())and(case when e.override_value_json is not null and e.override_expires_at>statement_timestamp()then e.override_value_json='true'::jsonb else e.boolean_value is true end))then raise exception 'documents_entitlement_required' using errcode='42501';end if;
 v_resident:=lower(x.role_code)in('owner','tenant_resident');v_tenant:=lower(x.role_code)='tenant_resident';
 if v_resident then select mp.party_id into v_party from identity.membership_parties mp where mp.membership_id=x.membership_key and mp.tenant_id=x.tenant_id;if v_party is null or x.scope_type<>'unit'then raise exception 'resident_party_and_unit_context_required' using errcode='42501';end if;
  if not v_tenant and not exists(select 1 from portfolio.ownerships o where o.tenant_id=x.tenant_id and o.unit_id=x.unit_id and o.party_id=v_party and o.valid_from<=current_date and(o.valid_to is null or o.valid_to>current_date))then raise exception 'ownership_required' using errcode='42501';end if;
  if v_tenant and not exists(select 1 from occupancy.leases l where l.tenant_id=x.tenant_id and l.unit_id=x.unit_id and l.tenant_party_id=v_party and l.status='active'and l.starts_on<=current_date and(l.ends_on is null or l.ends_on>current_date))then raise exception 'active_lease_required' using errcode='42501';end if;end if;
 with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end)
 select jsonb_build_object('documents',count(*),'published',count(*)filter(where published_at is not null),'legal_hold',count(*)filter(where legal_hold or exists(select 1 from documents.legal_holds h where h.document_id=allowed.id and h.status='active')),'expiring',count(*)filter(where expires_on between current_date and current_date+30))into v_summary from allowed;
 if p_view='documents'then with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),q as(select d.id,d.title,d.document_type,d.category,d.classification,d.organizational_owner,d.current_version,d.status,d.created_at,d.effective_on,d.expires_on,d.retention_policy_code,case when d.legal_hold or exists(select 1 from documents.legal_holds h where h.document_id=d.id and h.status='active')then'active'else'none'end legal_hold_status,v.sha256 hash,(v.id is not null)evidence_available,((select count(*)from documents.document_links l where l.document_id=d.id)+(select count(*)from documents.document_audit_links l where l.document_id=d.id))linked_entity_count,count(*)over()total_count from allowed d left join lateral(select x.id,x.sha256 from documents.document_versions x where x.document_id=d.id and x.version=d.current_version order by x.id limit 1)v on true where(p_id is null or d.id=p_id)and(p_status is null or d.status::text=p_status)and(p_classification is null or d.classification::text=p_classification)and(p_from is null or d.created_at::date>=p_from)and(p_to is null or d.created_at::date<=p_to)and(p_query is null or d.title ilike'%'||trim(p_query)||'%'or d.document_type ilike'%'||trim(p_query)||'%'or coalesce(d.category,'')ilike'%'||trim(p_query)||'%')order by d.created_at desc,d.id limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;
 elsif p_view='versions'then with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),q as(select v.id,v.document_id,d.title document_title,v.version,v.sha256 hash,v.mime_type,v.size_bytes,v.published_at,v.created_at,(v.object_path is not null)evidence_available,count(*)over()total_count from documents.document_versions v join allowed d on d.id=v.document_id where(p_id is null or v.id=p_id)order by v.created_at desc,v.id limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;
 elsif p_view='categories'then with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),q as(select coalesce(d.category,d.document_type)category,d.classification::text,count(*)document_count,max(d.created_at)latest_at,count(*)over()total_count from allowed d group by coalesce(d.category,d.document_type),d.classification order by document_count desc limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;
 elsif p_view='retention'then with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),q as(select r.id,r.document_id,d.title document_title,r.policy_code,r.retain_until,r.disposition_status,r.calculated_at,r.finalized_at,true snapshot_available,count(*)over()total_count from documents.retention_records r join allowed d on d.id=r.document_id where(p_status is null or r.disposition_status=p_status)order by r.calculated_at desc,r.id limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;
 elsif p_view='holds'then with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),q as(select h.id,h.document_id,d.title document_title,h.reason,h.status,h.applied_at,h.released_at,(h.evidence_hash is not null)evidence_available,count(*)over()total_count from documents.legal_holds h join allowed d on d.id=h.document_id where(p_status is null or h.status=p_status)order by h.applied_at desc,h.id limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;
 elsif p_view='evidence'then with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),q as(select d.id,d.title,d.current_version,v.sha256 hash,v.mime_type,v.size_bytes,(v.id is not null)evidence_available,v.created_at evidence_registered_at,count(*)over()total_count from allowed d left join lateral(select x.id,x.sha256,x.mime_type,x.size_bytes,x.created_at from documents.document_versions x where x.document_id=d.id and x.version=d.current_version order by x.id limit 1)v on true order by d.created_at desc limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;
 elsif p_view='links'then with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),all_links as(select l.id,l.document_id,l.entity_type,l.relation_type,l.created_at,case l.entity_type when'platform.tenant'then(select t.legal_name from platform.tenants t where t.id=l.entity_id)when'portfolio.property'then(select p.name from portfolio.properties p where p.id=l.entity_id)when'portfolio.building'then(select b.name from portfolio.buildings b where b.id=l.entity_id)when'portfolio.unit'then(select u.unit_code from portfolio.units u where u.id=l.entity_id)when'platform.contract'then(select c.contract_ref from platform.workspace_contracts c where c.id=l.entity_id)when'billing.invoice'then(select i.invoice_no::text from billing.invoices i where i.id=l.entity_id)when'finance.journal'then(select j.journal_no::text from finance.journals j where j.id=l.entity_id)when'maintenance.work_order'then(select w.title from maintenance.work_orders w where w.id=l.entity_id)when'governance.meeting'then(select m.title from governance.meetings m where m.id=l.entity_id)when'governance.resolution'then(select r.title from governance.resolutions r where r.id=l.entity_id)when'communications.post'then(select p.title from communications.posts p where p.id=l.entity_id)else'Authorized record'end entity_label from documents.document_links l union all select l.id,l.document_id,'audit.event',l.relation_type,l.created_at,(select a.action from audit.events a where a.id=l.audit_event_id)from documents.document_audit_links l),q as(select l.id,d.title document_title,l.entity_type,l.entity_label,l.relation_type,l.created_at,count(*)over()total_count from all_links l join allowed d on d.id=l.document_id order by l.created_at desc,l.id limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;
 else with allowed as(select d.* from documents.documents d where d.tenant_id=x.tenant_id and d.deleted_at is null and documents.customer_document_scope_matches(x.scope_type::text,x.property_id,x.building_id,x.unit_id,d.property_id)and case lower(x.role_code)
  when'association_admin'then true when'property_manager'then d.classification<>'restricted'
  when'president'then d.classification<>'restricted'and(d.document_type ilike'governance%'or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('governance.meeting','governance.resolution')))
  when'censor'then d.classification<>'restricted'and(d.document_type ilike any(array['audit%','financial%','governance%'])or exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type in('finance.journal','billing.invoice','governance.meeting','governance.resolution'))or exists(select 1 from documents.document_audit_links l where l.document_id=d.id))
  when'owner'then d.classification<>'restricted'and exists(select 1 from documents.document_links l where l.document_id=d.id and l.entity_type='portfolio.unit'and l.entity_id=x.unit_id)
  else d.classification='public'or exists(select 1 from documents.document_permissions a where a.document_id=d.id and a.tenant_id=x.tenant_id and(a.membership_id=x.membership_key or a.party_id=v_party)and a.valid_from<=statement_timestamp()and(a.valid_until is null or a.valid_until>statement_timestamp()))end),q as(select h.id,h.document_id,d.title document_title,h.event_type,h.status_from,h.status_to,h.reason,h.rule_version,(h.evidence_hash is not null)evidence_available,h.occurred_at,count(*)over()total_count from documents.lifecycle_events h join allowed d on d.id=h.document_id order by h.occurred_at desc,h.id desc limit p_limit offset p_offset)select coalesce(max(total_count),0),coalesce(jsonb_agg(to_jsonb(q)-'total_count'),'[]')into v_total,v_rows from q;end if;
 v_detail:=case when p_id is null then null else(select r from jsonb_array_elements(v_rows)r where r->>'id'=p_id::text limit 1)end;
 return jsonb_build_object('context',jsonb_build_object('id',x.id,'role',x.role_code,'scope',x.scope_type),'view',p_view,'total',coalesce(v_total,0),'rows',coalesce(v_rows,'[]'),'summary',v_summary,'detail',v_detail,'read_only',true,'storage_access',false,'signed_urls',false,'generated_at',statement_timestamp());
end $$;

commit;
